//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dts_agent.StandardMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StandardMessageResource_VN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StandardMessageResource_VN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dts_agent.StandardMessage.StandardMessageResource-VN", typeof(StandardMessageResource_VN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu của bạn để hoàn thành đơn hàng..
        /// </summary>
        internal static string ConfirmationPassword {
            get {
                return ResourceManager.GetString("ConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng chỉ không hợp lệ!.
        /// </summary>
        internal static string ErrorAdmintrativeLogin {
            get {
                return ResourceManager.GetString("ErrorAdmintrativeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sự cố kết nối máy chủ. Vui lòng tới thu ngân để được hỗ trợ..
        /// </summary>
        internal static string ErrorAskAssistanceFromCashier {
            get {
                return ResourceManager.GetString("ErrorAskAssistanceFromCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo hiện có trong sử dụng. Để tận dụng một quảng cáo mới, bạn phải kết thúc quảng cáo của mình trong quầy thu ngân..
        /// </summary>
        internal static string ErrorAvailPromoWithActivePromo {
            get {
                return ResourceManager.GetString("ErrorAvailPromoWithActivePromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu là bắt buộc..
        /// </summary>
        internal static string ErrorConfirmPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorConfirmPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xác nhận mã pin của bạn.
        /// </summary>
        internal static string ErrorConfirmPinCodeRequired {
            get {
                return ResourceManager.GetString("ErrorConfirmPinCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể {0} ngay bây giờ do sự cố kết nối {1}. Vui lòng tới thu ngân để được hỗ trợ..
        /// </summary>
        internal static string ErrorConnectionIssue {
            get {
                return ResourceManager.GetString("ErrorConnectionIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được để trống trường này..
        /// </summary>
        internal static string ErrorCPAllPasswordFieldIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPAllPasswordFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không được để trống..
        /// </summary>
        internal static string ErrorCPConfirmPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPConfirmPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại và xác nhận mật khẩu mới không được để trống..
        /// </summary>
        internal static string ErrorCPCurrentConfirmPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPCurrentConfirmPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại và mật khẩu mới không được để trống..
        /// </summary>
        internal static string ErrorCPCurrentNewPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPCurrentNewPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại không được để trống..
        /// </summary>
        internal static string ErrorCPCurrentPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPCurrentPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới và xác nhận mật khẩu mới không được để trống..
        /// </summary>
        internal static string ErrorCPNewConfirmPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPNewConfirmPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới không được để trống..
        /// </summary>
        internal static string ErrorCPNewPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPNewPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng đọc và chấp nhận các điều khoản và điều kiện..
        /// </summary>
        internal static string ErrorDoesntAgreeTNC {
            get {
                return ResourceManager.GetString("ErrorDoesntAgreeTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HẾT HÀNG.
        /// </summary>
        internal static string ErrorEloadCode {
            get {
                return ResourceManager.GetString("ErrorEloadCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực này là bắt buộc..
        /// </summary>
        internal static string ErrorFieldIsEmpty {
            get {
                return ResourceManager.GetString("ErrorFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng chỉ không hợp lệ..
        /// </summary>
        internal static string ErrorIncorrectCredential {
            get {
                return ResourceManager.GetString("ErrorIncorrectCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một phiên bản của Đại lý GO-CAFE đã chạy..
        /// </summary>
        internal static string ErrorInstanceAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorInstanceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có đủ số dư. Vui lòng nạp tiền để đăng nhập..
        /// </summary>
        internal static string ErrorInsufficientBalanceOnLogin {
            get {
                return ResourceManager.GetString("ErrorInsufficientBalanceOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ tiền. Nạp tiền ngay bây giờ để tiến hành giao dịch của bạn..
        /// </summary>
        internal static string ErrorInsufficientFund {
            get {
                return ResourceManager.GetString("ErrorInsufficientFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ tiền. Nạp tiền ngay để đăng nhập..
        /// </summary>
        internal static string ErrorInsuficientBalanceOrZeroBalance {
            get {
                return ResourceManager.GetString("ErrorInsuficientBalanceOrZeroBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin không hợp lệ.
        /// </summary>
        internal static string ErrorInvalidPin {
            get {
                return ResourceManager.GetString("ErrorInvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi. Vui lòng tới thu ngân để được hỗ trợ..
        /// </summary>
        internal static string ErrorNeedHelpFromCashier {
            get {
                return ResourceManager.GetString("ErrorNeedHelpFromCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới là bắt buộc..
        /// </summary>
        internal static string ErrorNewPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorNewPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có nhân viên thu ngân!.
        /// </summary>
        internal static string ErrorNoAvailableCashier {
            get {
                return ResourceManager.GetString("ErrorNoAvailableCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một quảng cáo từ danh sách..
        /// </summary>
        internal static string ErrorNoSelectedPromo {
            get {
                return ResourceManager.GetString("ErrorNoSelectedPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng này chỉ dành cho thành viên. Đăng ký ngay để tận hưởng đặc quyền thành viên..
        /// </summary>
        internal static string ErrorNotMember {
            get {
                return ResourceManager.GetString("ErrorNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng của bạn đã bị từ chối..
        /// </summary>
        internal static string ErrorOrderRejected {
            get {
                return ResourceManager.GetString("ErrorOrderRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới và xác nhận lại mật khẩu mới ..
        /// </summary>
        internal static string ErrorPasswordAndConfirmPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorPasswordAndConfirmPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới và mật khẩu xác nhận không khớp..
        /// </summary>
        internal static string ErrorPasswordAndConfirmPasswordIsNotEqual {
            get {
                return ResourceManager.GetString("ErrorPasswordAndConfirmPasswordIsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống..
        /// </summary>
        internal static string ErrorPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không chính xác..
        /// </summary>
        internal static string ErrorPasswordIsInvalid {
            get {
                return ResourceManager.GetString("ErrorPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 4 ký tự.
        /// </summary>
        internal static string ErrorPasswordLessThan4 {
            get {
                return ResourceManager.GetString("ErrorPasswordLessThan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới và mật khẩu xác nhận không khớp..
        /// </summary>
        internal static string ErrorPasswordNotMatchedToNewPassword {
            get {
                return ResourceManager.GetString("ErrorPasswordNotMatchedToNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chứa khoảng trắng ở đầu hoặc cuối..
        /// </summary>
        internal static string ErrorPasswordNotMeetRequiredFields {
            get {
                return ResourceManager.GetString("ErrorPasswordNotMeetRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã pin của bạn.
        /// </summary>
        internal static string ErrorPinCodeRequired {
            get {
                return ResourceManager.GetString("ErrorPinCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin phải dài 4 ký tự..
        /// </summary>
        internal static string ErrorPinLockIsLess4Character {
            get {
                return ResourceManager.GetString("ErrorPinLockIsLess4Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã pin của bạn không khớp..
        /// </summary>
        internal static string ErrorPinLockIsNotEqualToConfirmPin {
            get {
                return ResourceManager.GetString("ErrorPinLockIsNotEqualToConfirmPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vấn đề kết nối Internet. Xin liên hệ nhân viên thu ngân để được giúp đỡ..
        /// </summary>
        internal static string ErrorRequestTimedOut {
            get {
                return ResourceManager.GetString("ErrorRequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC này chưa được cấu hình đúng. Vui lòng liên hệ với Thu ngân để được hỗ trợ và nhấp vào nút thử lại..
        /// </summary>
        internal static string ErrorStationNotProperlyRegistered {
            get {
                return ResourceManager.GetString("ErrorStationNotProperlyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đăng xuất. Vui lòng tớithu ngân để được hỗ trợ..
        /// </summary>
        internal static string ErrorUnableToLogout {
            get {
                return ResourceManager.GetString("ErrorUnableToLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi không mong muốn. Vui lòng tới thu ngân để được hỗ trợ..
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng là bắt buộc..
        /// </summary>
        internal static string ErrorUsernameIsEmpty {
            get {
                return ResourceManager.GetString("ErrorUsernameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng phải có ít nhất 4 ký tự.
        /// </summary>
        internal static string ErrorUsernameLessThan4 {
            get {
                return ResourceManager.GetString("ErrorUsernameLessThan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đạt tới giới hạn..
        /// </summary>
        internal static string ErrorValidateStock {
            get {
                return ResourceManager.GetString("ErrorValidateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng hiện không có sẵn. Vui lòng tới thu ngân để được hỗ trợ..
        /// </summary>
        internal static string NoActiveCashierMessage {
            get {
                return ResourceManager.GetString("NoActiveCashierMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng của bạn đã được gửi thành công.
        /// </summary>
        internal static string OrderSuccesfulMessage {
            get {
                return ResourceManager.GetString("OrderSuccesfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá:.
        /// </summary>
        internal static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã pin thứ hai là bắt buộc.
        /// </summary>
        internal static string RetryPinCode {
            get {
                return ResourceManager.GetString("RetryPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ uống.
        /// </summary>
        internal static string StoreItemCategoryBeverage {
            get {
                return ResourceManager.GetString("StoreItemCategoryBeverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELOAD/EPINS.
        /// </summary>
        internal static string StoreItemCategoryEloadEpins {
            get {
                return ResourceManager.GetString("StoreItemCategoryEloadEpins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ ăn.
        /// </summary>
        internal static string StoreItemCategoryFood {
            get {
                return ResourceManager.GetString("StoreItemCategoryFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string StoreItemCategoryOthers {
            get {
                return ResourceManager.GetString("StoreItemCategoryOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu ngân nạp tiền thành công!.
        /// </summary>
        internal static string SuccessCashierTopup {
            get {
                return ResourceManager.GetString("SuccessCashierTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua xong. Mã pin của bạn đã được gửi đến email của bạn và có thể xem được trong lịch sử giao dịch của bạn..
        /// </summary>
        internal static string SuccessELoadPurchase {
            get {
                return ResourceManager.GetString("SuccessELoadPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng của bạn đã được chấp nhận..
        /// </summary>
        internal static string SuccessOrderAccepted {
            get {
                return ResourceManager.GetString("SuccessOrderAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng của bạn đã được đặt. Vui lòng cho nhân viên thu ngân một vài phút để xử lý yêu cầu của bạn..
        /// </summary>
        internal static string SuccessProceedOrder {
            get {
                return ResourceManager.GetString("SuccessProceedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công {0} {1} của bạn..
        /// </summary>
        internal static string SuccessProcess {
            get {
                return ResourceManager.GetString("SuccessProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã mua thành công {0}.
        /// </summary>
        internal static string SuccessPromoPurchase {
            get {
                return ResourceManager.GetString("SuccessPromoPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu giảm giá được sử dụng thành công.
        /// </summary>
        internal static string SuccessRedeemedCoupon {
            get {
                return ResourceManager.GetString("SuccessRedeemedCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đổi thành công một phiếu giảm giá. {0} (Lưu ý: Thời gian phiếu sẽ không hiển thị nếu được đổi trong khi sử dụng quảng cáo).
        /// </summary>
        internal static string SuccessRedeemedCoupon2 {
            get {
                return ResourceManager.GetString("SuccessRedeemedCoupon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công thông tin của bạn..
        /// </summary>
        internal static string SuccessUpdateInformation {
            get {
                return ResourceManager.GetString("SuccessUpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được chỉ định.
        /// </summary>
        internal static string TransactBranchRegisterIsNull {
            get {
                return ResourceManager.GetString("TransactBranchRegisterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tài khoản.
        /// </summary>
        internal static string TransactionWordAccount {
            get {
                return ResourceManager.GetString("TransactionWordAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to áp dụng quảng cáo cho.
        /// </summary>
        internal static string TransactionWordAppliedPromoTo {
            get {
                return ResourceManager.GetString("TransactionWordAppliedPromoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã được chấp nhận.
        /// </summary>
        internal static string TransactOrderAccepted {
            get {
                return ResourceManager.GetString("TransactOrderAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chờ xử lý.
        /// </summary>
        internal static string TransactOrderPending {
            get {
                return ResourceManager.GetString("TransactOrderPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sẵn sàng giao hàng.
        /// </summary>
        internal static string TransactOrderReadyToDeliver {
            get {
                return ResourceManager.GetString("TransactOrderReadyToDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nhận.
        /// </summary>
        internal static string TransactOrderReceived {
            get {
                return ResourceManager.GetString("TransactOrderReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị từ chối.
        /// </summary>
        internal static string TransactOrderReject {
            get {
                return ResourceManager.GetString("TransactOrderReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áp dụng.
        /// </summary>
        internal static string TransactWordApply {
            get {
                return ResourceManager.GetString("TransactWordApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áp dụng khuyến mãi.
        /// </summary>
        internal static string TransactWordApplyPromo {
            get {
                return ResourceManager.GetString("TransactWordApplyPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string TransactWordChangePassword {
            get {
                return ResourceManager.GetString("TransactWordChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối.
        /// </summary>
        internal static string TransactWordConnect {
            get {
                return ResourceManager.GetString("TransactWordConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu mua hàng.
        /// </summary>
        internal static string TransactWordCoupon {
            get {
                return ResourceManager.GetString("TransactWordCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string TransactWordForPlural {
            get {
                return ResourceManager.GetString("TransactWordForPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string TransactWordInformation {
            get {
                return ResourceManager.GetString("TransactWordInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mạng.
        /// </summary>
        internal static string TransactWordInternet {
            get {
                return ResourceManager.GetString("TransactWordInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoại tuyến.
        /// </summary>
        internal static string TransactWordOffline {
            get {
                return ResourceManager.GetString("TransactWordOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string TransactWordPassword {
            get {
                return ResourceManager.GetString("TransactWordPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo.
        /// </summary>
        internal static string TransactWordPromo {
            get {
                return ResourceManager.GetString("TransactWordPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuộc lại.
        /// </summary>
        internal static string TransactWordRedeem {
            get {
                return ResourceManager.GetString("TransactWordRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu.
        /// </summary>
        internal static string TransactWordSaved {
            get {
                return ResourceManager.GetString("TransactWordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ.
        /// </summary>
        internal static string TransactWordServer {
            get {
                return ResourceManager.GetString("TransactWordServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật.
        /// </summary>
        internal static string TransactWordUpdated {
            get {
                return ResourceManager.GetString("TransactWordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng trống.
        /// </summary>
        internal static string TransactWordVoidStatus {
            get {
                return ResourceManager.GetString("TransactWordVoidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu trước đó của bạn CÓ THỂ bị hủy nếu bạn chuyển sang các trang khác. Bạn có chắc muốn tiếp tục?.
        /// </summary>
        internal static string WarningCancelRequests {
            get {
                return ResourceManager.GetString("WarningCancelRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn {0} này {1} không? Chỉ một {1} tại một thời điểm có thể được kích hoạt, trước đây đã chọn hoặc không sử dụng {1} sẽ bị mất..
        /// </summary>
        internal static string WarningConfirmationApplication {
            get {
                return ResourceManager.GetString("WarningConfirmationApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been granted bonus airtime using your bonus load..
        /// </summary>
        internal static string WarningConfirmationBonusLoadUsage {
            get {
                return ResourceManager.GetString("WarningConfirmationBonusLoadUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn thoát?.
        /// </summary>
        internal static string WarningConfirmationLogoutUser {
            get {
                return ResourceManager.GetString("WarningConfirmationLogoutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restart this PC?.
        /// </summary>
        internal static string WarningConfirmationRestartPC {
            get {
                return ResourceManager.GetString("WarningConfirmationRestartPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to shutdown this PC?.
        /// </summary>
        internal static string WarningConfirmationShutdownPC {
            get {
                return ResourceManager.GetString("WarningConfirmationShutdownPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn tắt các tính năng bảo mật? PC này sẽ khởi động lại ngay khi áp dụng các thay đổi..
        /// </summary>
        internal static string WarningDisableSecurityPolicy {
            get {
                return ResourceManager.GetString("WarningDisableSecurityPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy thử lại trong {0}..
        /// </summary>
        internal static string WarningDuringButtonCoolDown {
            get {
                return ResourceManager.GetString("WarningDuringButtonCoolDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC này sẽ khởi động lại ngay khi áp dụng các thay đổi..
        /// </summary>
        internal static string WarningEnableSecurityPolicy {
            get {
                return ResourceManager.GetString("WarningEnableSecurityPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn ẩn trạng thái thời gian?.
        /// </summary>
        internal static string WarningHideAirtimeNotification {
            get {
                return ResourceManager.GetString("WarningHideAirtimeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn ẩn trạng thái thưởng?.
        /// </summary>
        internal static string WarningHideBonusLoadStatus {
            get {
                return ResourceManager.GetString("WarningHideBonusLoadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn ẩn trạng thái đơn hàng?.
        /// </summary>
        internal static string WarningHideOrderStatus {
            get {
                return ResourceManager.GetString("WarningHideOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn thoát?.
        /// </summary>
        internal static string WarningLogout {
            get {
                return ResourceManager.GetString("WarningLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cố gắng {1} còn lại..
        /// </summary>
        internal static string WarningNumberAttempts {
            get {
                return ResourceManager.GetString("WarningNumberAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo, bạn vẫn có một phiếu giảm giá hoạt động. Hệ thống sẽ tiếp tục sử dụng nó ngay cả khi bạn tận dụng quảng cáo..
        /// </summary>
        internal static string WarningPromoWhenHaveCoupon {
            get {
                return ResourceManager.GetString("WarningPromoWhenHaveCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn gỡ bỏ không.
        /// </summary>
        internal static string WarningRemoveShoppingBag1 {
            get {
                return ResourceManager.GetString("WarningRemoveShoppingBag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to từ túi mua sắm của bạn?.
        /// </summary>
        internal static string WarningRemoveShoppingBag2 {
            get {
                return ResourceManager.GetString("WarningRemoveShoppingBag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối mạng. Vui lòng liên hệ với Nhân viên thu ngân để được hỗ trợ và nhấn vào nút thử lại..
        /// </summary>
        internal static string WarningRetryReconnection {
            get {
                return ResourceManager.GetString("WarningRetryReconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn gỡ cài đặt ứng dụng đại lý?.
        /// </summary>
        internal static string WarningUninstall {
            get {
                return ResourceManager.GetString("WarningUninstall", resourceCulture);
            }
        }
    }
}
