//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dts_agent.StandardMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StandardMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StandardMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dts_agent.StandardMessage.StandardMessageResource", typeof(StandardMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password to complete your order..
        /// </summary>
        internal static string ConfirmationPassword {
            get {
                return ResourceManager.GetString("ConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credential!.
        /// </summary>
        internal static string ErrorAdmintrativeLogin {
            get {
                return ResourceManager.GetString("ErrorAdmintrativeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection issue. Please proceed to cashier for assistance..
        /// </summary>
        internal static string ErrorAskAssistanceFromCashier {
            get {
                return ResourceManager.GetString("ErrorAskAssistanceFromCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing promo in use. To avail a new promo, you have to end your promo in cashier..
        /// </summary>
        internal static string ErrorAvailPromoWithActivePromo {
            get {
                return ResourceManager.GetString("ErrorAvailPromoWithActivePromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password field is required..
        /// </summary>
        internal static string ErrorConfirmPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorConfirmPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your pin code.
        /// </summary>
        internal static string ErrorConfirmPinCodeRequired {
            get {
                return ResourceManager.GetString("ErrorConfirmPinCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot {0} right now due to {1} connection issue. Please proceed to cashier for assistance..
        /// </summary>
        internal static string ErrorConnectionIssue {
            get {
                return ResourceManager.GetString("ErrorConnectionIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields should not be empty..
        /// </summary>
        internal static string ErrorCPAllPasswordFieldIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPAllPasswordFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password should not be empty..
        /// </summary>
        internal static string ErrorCPConfirmPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPConfirmPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password and confirm new password should not be empty..
        /// </summary>
        internal static string ErrorCPCurrentConfirmPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPCurrentConfirmPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password and new password should not be empty..
        /// </summary>
        internal static string ErrorCPCurrentNewPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPCurrentNewPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password should not be empty..
        /// </summary>
        internal static string ErrorCPCurrentPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPCurrentPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm new password should not be empty..
        /// </summary>
        internal static string ErrorCPNewConfirmPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPNewConfirmPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password should not be empty..
        /// </summary>
        internal static string ErrorCPNewPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCPNewPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read and accept the terms and condition..
        /// </summary>
        internal static string ErrorDoesntAgreeTNC {
            get {
                return ResourceManager.GetString("ErrorDoesntAgreeTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT OF STOCK.
        /// </summary>
        internal static string ErrorEloadCode {
            get {
                return ResourceManager.GetString("ErrorEloadCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string ErrorFieldIsEmpty {
            get {
                return ResourceManager.GetString("ErrorFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credential..
        /// </summary>
        internal static string ErrorIncorrectCredential {
            get {
                return ResourceManager.GetString("ErrorIncorrectCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of GO-CAFE Agent is already running..
        /// </summary>
        internal static string ErrorInstanceAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorInstanceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have insufficient balance. Please topup to login..
        /// </summary>
        internal static string ErrorInsufficientBalanceOnLogin {
            get {
                return ResourceManager.GetString("ErrorInsufficientBalanceOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds. Topup now to proceed with your transaction..
        /// </summary>
        internal static string ErrorInsufficientFund {
            get {
                return ResourceManager.GetString("ErrorInsufficientFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds. Topup now to login..
        /// </summary>
        internal static string ErrorInsuficientBalanceOrZeroBalance {
            get {
                return ResourceManager.GetString("ErrorInsuficientBalanceOrZeroBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pin.
        /// </summary>
        internal static string ErrorInvalidPin {
            get {
                return ResourceManager.GetString("ErrorInvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please proceed to cashier for assistance..
        /// </summary>
        internal static string ErrorNeedHelpFromCashier {
            get {
                return ResourceManager.GetString("ErrorNeedHelpFromCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password field is required..
        /// </summary>
        internal static string ErrorNewPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorNewPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available Cashier!.
        /// </summary>
        internal static string ErrorNoAvailableCashier {
            get {
                return ResourceManager.GetString("ErrorNoAvailableCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a promo from the list..
        /// </summary>
        internal static string ErrorNoSelectedPromo {
            get {
                return ResourceManager.GetString("ErrorNoSelectedPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is for members only. Sign up now to enjoy member privileges..
        /// </summary>
        internal static string ErrorNotMember {
            get {
                return ResourceManager.GetString("ErrorNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been rejected..
        /// </summary>
        internal static string ErrorOrderRejected {
            get {
                return ResourceManager.GetString("ErrorOrderRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password fields are required..
        /// </summary>
        internal static string ErrorPasswordAndConfirmPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorPasswordAndConfirmPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password do not match..
        /// </summary>
        internal static string ErrorPasswordAndConfirmPasswordIsNotEqual {
            get {
                return ResourceManager.GetString("ErrorPasswordAndConfirmPasswordIsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field should not be empty..
        /// </summary>
        internal static string ErrorPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect old password..
        /// </summary>
        internal static string ErrorPasswordIsInvalid {
            get {
                return ResourceManager.GetString("ErrorPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 4 characters.
        /// </summary>
        internal static string ErrorPasswordLessThan4 {
            get {
                return ResourceManager.GetString("ErrorPasswordLessThan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password do not match..
        /// </summary>
        internal static string ErrorPasswordNotMatchedToNewPassword {
            get {
                return ResourceManager.GetString("ErrorPasswordNotMatchedToNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot contain white space at the beginning or at the end..
        /// </summary>
        internal static string ErrorPasswordNotMeetRequiredFields {
            get {
                return ResourceManager.GetString("ErrorPasswordNotMeetRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your pin code.
        /// </summary>
        internal static string ErrorPinCodeRequired {
            get {
                return ResourceManager.GetString("ErrorPinCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin should be 4 characters long..
        /// </summary>
        internal static string ErrorPinLockIsLess4Character {
            get {
                return ResourceManager.GetString("ErrorPinLockIsLess4Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pin codes do not match..
        /// </summary>
        internal static string ErrorPinLockIsNotEqualToConfirmPin {
            get {
                return ResourceManager.GetString("ErrorPinLockIsNotEqualToConfirmPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection issue. Please ask assistance from the cashier..
        /// </summary>
        internal static string ErrorRequestTimedOut {
            get {
                return ResourceManager.GetString("ErrorRequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PC hasn&apos;t been configured properly. Please contact the Cashier for assistance and click on the retry button..
        /// </summary>
        internal static string ErrorStationNotProperlyRegistered {
            get {
                return ResourceManager.GetString("ErrorStationNotProperlyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to logout. Please proceed to cashier for assistance..
        /// </summary>
        internal static string ErrorUnableToLogout {
            get {
                return ResourceManager.GetString("ErrorUnableToLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please proceed to cashier for assistance..
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username field is required..
        /// </summary>
        internal static string ErrorUsernameIsEmpty {
            get {
                return ResourceManager.GetString("ErrorUsernameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 4 characters.
        /// </summary>
        internal static string ErrorUsernameLessThan4 {
            get {
                return ResourceManager.GetString("ErrorUsernameLessThan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock reach its limit!.
        /// </summary>
        internal static string ErrorValidateStock {
            get {
                return ResourceManager.GetString("ErrorValidateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store is currently unavailable. Please proceed to cashier for assistance..
        /// </summary>
        internal static string NoActiveCashierMessage {
            get {
                return ResourceManager.GetString("NoActiveCashierMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been submitted successfully.
        /// </summary>
        internal static string OrderSuccesfulMessage {
            get {
                return ResourceManager.GetString("OrderSuccesfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: .
        /// </summary>
        internal static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second pin code is required.
        /// </summary>
        internal static string RetryPinCode {
            get {
                return ResourceManager.GetString("RetryPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beverage.
        /// </summary>
        internal static string StoreItemCategoryBeverage {
            get {
                return ResourceManager.GetString("StoreItemCategoryBeverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELOAD/EPINS.
        /// </summary>
        internal static string StoreItemCategoryEloadEpins {
            get {
                return ResourceManager.GetString("StoreItemCategoryEloadEpins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string StoreItemCategoryFood {
            get {
                return ResourceManager.GetString("StoreItemCategoryFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string StoreItemCategoryOthers {
            get {
                return ResourceManager.GetString("StoreItemCategoryOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier Top-up Successful!.
        /// </summary>
        internal static string SuccessCashierTopup {
            get {
                return ResourceManager.GetString("SuccessCashierTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase completed. Your pin has been sent to your email and can be viewed in your transaction history..
        /// </summary>
        internal static string SuccessELoadPurchase {
            get {
                return ResourceManager.GetString("SuccessELoadPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been accepted..
        /// </summary>
        internal static string SuccessOrderAccepted {
            get {
                return ResourceManager.GetString("SuccessOrderAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been placed. Please give the cashier a few minutes to process your request..
        /// </summary>
        internal static string SuccessProceedOrder {
            get {
                return ResourceManager.GetString("SuccessProceedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully {0} your {1}..
        /// </summary>
        internal static string SuccessProcess {
            get {
                return ResourceManager.GetString("SuccessProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully purchased {0}.
        /// </summary>
        internal static string SuccessPromoPurchase {
            get {
                return ResourceManager.GetString("SuccessPromoPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon successfully redeemed.
        /// </summary>
        internal static string SuccessRedeemedCoupon {
            get {
                return ResourceManager.GetString("SuccessRedeemedCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully redeemed a coupon. {0}(Note: Coupon time will not be visible if redeemed while using a promo).
        /// </summary>
        internal static string SuccessRedeemedCoupon2 {
            get {
                return ResourceManager.GetString("SuccessRedeemedCoupon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated your information..
        /// </summary>
        internal static string SuccessUpdateInformation {
            get {
                return ResourceManager.GetString("SuccessUpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        internal static string TransactBranchRegisterIsNull {
            get {
                return ResourceManager.GetString("TransactBranchRegisterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        internal static string TransactionWordAccount {
            get {
                return ResourceManager.GetString("TransactionWordAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to applied promo to.
        /// </summary>
        internal static string TransactionWordAppliedPromoTo {
            get {
                return ResourceManager.GetString("TransactionWordAppliedPromoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string TransactOrderAccepted {
            get {
                return ResourceManager.GetString("TransactOrderAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string TransactOrderPending {
            get {
                return ResourceManager.GetString("TransactOrderPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadyToDeliver.
        /// </summary>
        internal static string TransactOrderReadyToDeliver {
            get {
                return ResourceManager.GetString("TransactOrderReadyToDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string TransactOrderReceived {
            get {
                return ResourceManager.GetString("TransactOrderReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string TransactOrderReject {
            get {
                return ResourceManager.GetString("TransactOrderReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        internal static string TransactWordApply {
            get {
                return ResourceManager.GetString("TransactWordApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply promo.
        /// </summary>
        internal static string TransactWordApplyPromo {
            get {
                return ResourceManager.GetString("TransactWordApplyPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change password.
        /// </summary>
        internal static string TransactWordChangePassword {
            get {
                return ResourceManager.GetString("TransactWordChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connect.
        /// </summary>
        internal static string TransactWordConnect {
            get {
                return ResourceManager.GetString("TransactWordConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupon.
        /// </summary>
        internal static string TransactWordCoupon {
            get {
                return ResourceManager.GetString("TransactWordCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string TransactWordForPlural {
            get {
                return ResourceManager.GetString("TransactWordForPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information.
        /// </summary>
        internal static string TransactWordInformation {
            get {
                return ResourceManager.GetString("TransactWordInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string TransactWordInternet {
            get {
                return ResourceManager.GetString("TransactWordInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFLINE.
        /// </summary>
        internal static string TransactWordOffline {
            get {
                return ResourceManager.GetString("TransactWordOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string TransactWordPassword {
            get {
                return ResourceManager.GetString("TransactWordPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to promo.
        /// </summary>
        internal static string TransactWordPromo {
            get {
                return ResourceManager.GetString("TransactWordPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redeem.
        /// </summary>
        internal static string TransactWordRedeem {
            get {
                return ResourceManager.GetString("TransactWordRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved.
        /// </summary>
        internal static string TransactWordSaved {
            get {
                return ResourceManager.GetString("TransactWordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server.
        /// </summary>
        internal static string TransactWordServer {
            get {
                return ResourceManager.GetString("TransactWordServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated.
        /// </summary>
        internal static string TransactWordUpdated {
            get {
                return ResourceManager.GetString("TransactWordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Status.
        /// </summary>
        internal static string TransactWordVoidStatus {
            get {
                return ResourceManager.GetString("TransactWordVoidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your previous request MAY get canceled if you move to other pages. Are you sure you want to proceed?.
        /// </summary>
        internal static string WarningCancelRequests {
            get {
                return ResourceManager.GetString("WarningCancelRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to {0} this {1}? Only one {1} at a time can be active, previously claimed or unused {1} will be lost..
        /// </summary>
        internal static string WarningConfirmationApplication {
            get {
                return ResourceManager.GetString("WarningConfirmationApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been granted bonus airtime using your bonus load..
        /// </summary>
        internal static string WarningConfirmationBonusLoadUsage {
            get {
                return ResourceManager.GetString("WarningConfirmationBonusLoadUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string WarningConfirmationLogoutUser {
            get {
                return ResourceManager.GetString("WarningConfirmationLogoutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restart this PC?.
        /// </summary>
        internal static string WarningConfirmationRestartPC {
            get {
                return ResourceManager.GetString("WarningConfirmationRestartPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to shutdown this PC?.
        /// </summary>
        internal static string WarningConfirmationShutdownPC {
            get {
                return ResourceManager.GetString("WarningConfirmationShutdownPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to disable security features? This PC will restart upon applying changes..
        /// </summary>
        internal static string WarningDisableSecurityPolicy {
            get {
                return ResourceManager.GetString("WarningDisableSecurityPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again in {0}..
        /// </summary>
        internal static string WarningDuringButtonCoolDown {
            get {
                return ResourceManager.GetString("WarningDuringButtonCoolDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PC will restart upon applying changes..
        /// </summary>
        internal static string WarningEnableSecurityPolicy {
            get {
                return ResourceManager.GetString("WarningEnableSecurityPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to hide airtime status?.
        /// </summary>
        internal static string WarningHideAirtimeNotification {
            get {
                return ResourceManager.GetString("WarningHideAirtimeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to hide bonus load status?.
        /// </summary>
        internal static string WarningHideBonusLoadStatus {
            get {
                return ResourceManager.GetString("WarningHideBonusLoadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to hide order status?.
        /// </summary>
        internal static string WarningHideOrderStatus {
            get {
                return ResourceManager.GetString("WarningHideOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string WarningLogout {
            get {
                return ResourceManager.GetString("WarningLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attempt{1} remaining..
        /// </summary>
        internal static string WarningNumberAttempts {
            get {
                return ResourceManager.GetString("WarningNumberAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, you still have an active coupon.  System will continue consuming it even when you avail a promo..
        /// </summary>
        internal static string WarningPromoWhenHaveCoupon {
            get {
                return ResourceManager.GetString("WarningPromoWhenHaveCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove.
        /// </summary>
        internal static string WarningRemoveShoppingBag1 {
            get {
                return ResourceManager.GetString("WarningRemoveShoppingBag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from your shopping bag?.
        /// </summary>
        internal static string WarningRemoveShoppingBag2 {
            get {
                return ResourceManager.GetString("WarningRemoveShoppingBag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection error. Please contact the Cashier for assisstance and click on the retry button..
        /// </summary>
        internal static string WarningRetryReconnection {
            get {
                return ResourceManager.GetString("WarningRetryReconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to uninstall the agent app?.
        /// </summary>
        internal static string WarningUninstall {
            get {
                return ResourceManager.GetString("WarningUninstall", resourceCulture);
            }
        }
    }
}
