//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dts_shared.ResponseMessageResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessageResource_VND {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageResource_VND() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dts_shared.ResponseMessageResource.ErrorMessageResource_VND", typeof(ErrorMessageResource_VND).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu về chúng tôi không tồn tại.
        /// </summary>
        internal static string AboutUsNotExist {
            get {
                return ResourceManager.GetString("AboutUsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn hiện đang bị vô hiệu hóa..
        /// </summary>
        internal static string AccountDeactivated {
            get {
                return ResourceManager.GetString("AccountDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đã hết hạn..
        /// </summary>
        internal static string AccountExpired {
            get {
                return ResourceManager.GetString("AccountExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không có số dư cho an ninh mạng này. Hãy đến quầy thu ngân để làm topup đầu tiên của bạn..
        /// </summary>
        internal static string AccountHasNoBalance {
            get {
                return ResourceManager.GetString("AccountHasNoBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng thêm sản phẩm từ kho của bạn..
        /// </summary>
        internal static string AddProductsFromInventory {
            get {
                return ResourceManager.GetString("AddProductsFromInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệnh điều chỉnh không tồn tại..
        /// </summary>
        internal static string AdjustmentOrderNotExist {
            get {
                return ResourceManager.GetString("AdjustmentOrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm điều chỉnh không tồn tại..
        /// </summary>
        internal static string AdjustmentProductNotExist {
            get {
                return ResourceManager.GetString("AdjustmentProductNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền đưa ra không bằng giá khuyến mãi..
        /// </summary>
        internal static string AmountGivenNotEqualToPromoPrice {
            get {
                return ResourceManager.GetString("AmountGivenNotEqualToPromoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền không nên bằng 0 hoặc âm..
        /// </summary>
        internal static string AmountZeroOrNegative {
            get {
                return ResourceManager.GetString("AmountZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận hết hiệu lực hoặc trống.
        /// </summary>
        internal static string ApprovalCodeEmpty {
            get {
                return ResourceManager.GetString("ApprovalCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví tiền thưởng không tồn tại..
        /// </summary>
        internal static string BonusLoadWalletNotExist {
            get {
                return ResourceManager.GetString("BonusLoadWalletNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh này đã tồn tại cho cybercafe.
        /// </summary>
        internal static string BranchAlreadyExist {
            get {
                return ResourceManager.GetString("BranchAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh từ nhật ký giao dịch và lệnh bán hàng không khớp..
        /// </summary>
        internal static string BranchAndSalesOrderNotMatch {
            get {
                return ResourceManager.GetString("BranchAndSalesOrderNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư chi nhánh không tồn tại.
        /// </summary>
        internal static string BranchBalanceNotExist {
            get {
                return ResourceManager.GetString("BranchBalanceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình cơ sở không tồn tại.
        /// </summary>
        internal static string BranchConfigurationNotExist {
            get {
                return ResourceManager.GetString("BranchConfigurationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng hiện đang bị vô hiệu hóa ở chi nhánh này.
        /// </summary>
        internal static string BranchFeatureDeactivated {
            get {
                return ResourceManager.GetString("BranchFeatureDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm không tồn tại ở chi nhánh này.
        /// </summary>
        internal static string BranchGroupNotExist {
            get {
                return ResourceManager.GetString("BranchGroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập chi nhánh và địa chỉ mac không có giá trị cùng một lúc.
        /// </summary>
        internal static string BranchIDAndMacAddressNull {
            get {
                return ResourceManager.GetString("BranchIDAndMacAddressNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh có số dư không đủ.
        /// </summary>
        internal static string BranchInsufficientBalance {
            get {
                return ResourceManager.GetString("BranchInsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh tồn kho không tồn tại..
        /// </summary>
        internal static string BranchInventoryNotExist {
            get {
                return ResourceManager.GetString("BranchInventoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh không tồn tại.
        /// </summary>
        internal static string BranchNotExist {
            get {
                return ResourceManager.GetString("BranchNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán lẻ chi nhánh không tồn tại..
        /// </summary>
        internal static string BranchRetailPricingNotExist {
            get {
                return ResourceManager.GetString("BranchRetailPricingNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy phiên bản tại chi nhánh.
        /// </summary>
        internal static string BranchVersionNotFound {
            get {
                return ResourceManager.GetString("BranchVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffet Airtime không tồn tại..
        /// </summary>
        internal static string BuffetAirtimeNotExist {
            get {
                return ResourceManager.GetString("BuffetAirtimeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể từ chối đơn đặt hàng từ các chi nhánh khác nhau..
        /// </summary>
        internal static string CannoRejectSalesOrderFromDifferentBranch {
            get {
                return ResourceManager.GetString("CannoRejectSalesOrderFromDifferentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chấp nhận đơn đặt hàng từ một chi nhánh khác..
        /// </summary>
        internal static string CannotAcceptSalesOrderFromDifferentBranch {
            get {
                return ResourceManager.GetString("CannotAcceptSalesOrderFromDifferentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm đơn đặt hàng với bán lẻ trống..
        /// </summary>
        internal static string CannotAddOrderEmptySalesRetail {
            get {
                return ResourceManager.GetString("CannotAddOrderEmptySalesRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xử lý một lệnh điều chỉnh hàng tồn kho không chờ xử lý..
        /// </summary>
        internal static string CannotProcessNonPendingInventoryAdjustmentOrder {
            get {
                return ResourceManager.GetString("CannotProcessNonPendingInventoryAdjustmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xử lý một lệnh điều chỉnh bán hàng không chờ xử lý..
        /// </summary>
        internal static string CannotProcessNonPendingSalesAdjustmentOrder {
            get {
                return ResourceManager.GetString("CannotProcessNonPendingSalesAdjustmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm thu ngân này không tồn tại.
        /// </summary>
        internal static string CashierGroupNotExist {
            get {
                return ResourceManager.GetString("CashierGroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy phép của nhóm thu ngân này không tồn tại.
        /// </summary>
        internal static string CashierGroupPermissionNotExist {
            get {
                return ResourceManager.GetString("CashierGroupPermissionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu ngân hiện không ở đây.
        /// </summary>
        internal static string CashierNotExist {
            get {
                return ResourceManager.GetString("CashierNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên thu ngân này chưa được đăng ký.
        /// </summary>
        internal static string CashierNotRegistered {
            get {
                return ResourceManager.GetString("CashierNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký ca làm việc thu ngân không tồn tại.
        /// </summary>
        internal static string CashierSessionLogNotExist {
            get {
                return ResourceManager.GetString("CashierSessionLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca làm việc thu ngân này không tồn tại.
        /// </summary>
        internal static string CashierSessionNotExist {
            get {
                return ResourceManager.GetString("CashierSessionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên thu ngân chưa kết thúc ca làm việc.
        /// </summary>
        internal static string CashierShiftNotEnded {
            get {
                return ResourceManager.GetString("CashierShiftNotEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền thu ngân không tồn tại.
        /// </summary>
        internal static string CashierStationNotExist {
            get {
                return ResourceManager.GetString("CashierStationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố không tồn tại..
        /// </summary>
        internal static string CityNotExist {
            get {
                return ResourceManager.GetString("CityNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký khách hàng thân thiết không tồn tại.
        /// </summary>
        internal static string ClientLoyaltyLogNotExist {
            get {
                return ResourceManager.GetString("ClientLoyaltyLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên của khách hàng đã hết hạn..
        /// </summary>
        internal static string ClientSessionExpired {
            get {
                return ResourceManager.GetString("ClientSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các mã sau đã tồn tại (s) trên hệ thống:.
        /// </summary>
        internal static string CodeAlreadyExist {
            get {
                return ResourceManager.GetString("CodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa một mã đã được sử dụng..
        /// </summary>
        internal static string CodeAlreadyUsedCantDelete {
            get {
                return ResourceManager.GetString("CodeAlreadyUsedCantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có nhiều lần xuất hiện của các mã sau (s) :.
        /// </summary>
        internal static string CodeMultipleOccurence {
            get {
                return ResourceManager.GetString("CodeMultipleOccurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không tồn tại.
        /// </summary>
        internal static string CodeNotExist {
            get {
                return ResourceManager.GetString("CodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại mã đã tồn tại..
        /// </summary>
        internal static string CodeTypeNameAlreadyExist {
            get {
                return ResourceManager.GetString("CodeTypeNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại mã không tồn tại.
        /// </summary>
        internal static string CodeTypeNotExist {
            get {
                return ResourceManager.GetString("CodeTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình công ty này không tồn tại.
        /// </summary>
        internal static string CompanyConfigurationNotExist {
            get {
                return ResourceManager.GetString("CompanyConfigurationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập loại thành viên công ty không tồn tại..
        /// </summary>
        internal static string CompanyMemberTypeNotExist {
            get {
                return ResourceManager.GetString("CompanyMemberTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập loại thành viên công ty không được cấu hình.
        /// </summary>
        internal static string CompanyMemberTypeSetupNotConfigured {
            get {
                return ResourceManager.GetString("CompanyMemberTypeSetupNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty này không tồn tại.
        /// </summary>
        internal static string CompanyNotExist {
            get {
                return ResourceManager.GetString("CompanyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phần sản phẩm tổng hợp không tồn tại..
        /// </summary>
        internal static string CompositeProductComponentNotExist {
            get {
                return ResourceManager.GetString("CompositeProductComponentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm tổng hợp không tồn tại..
        /// </summary>
        internal static string CompositeProductNotExist {
            get {
                return ResourceManager.GetString("CompositeProductNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đất nước không tồn tại..
        /// </summary>
        internal static string CountryNotExist {
            get {
                return ResourceManager.GetString("CountryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher đã hết hạn.
        /// </summary>
        internal static string CouponAlreadyExpired {
            get {
                return ResourceManager.GetString("CouponAlreadyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vẫn có 1 voucher đang sử dụng. Giao dịch bị từ chối.
        /// </summary>
        internal static string CouponInUsePurchaseRejected {
            get {
                return ResourceManager.GetString("CouponInUsePurchaseRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu giảm giá bạn sắp sử dụng không áp dụng cho loại máy trạm này..
        /// </summary>
        internal static string CouponNotApplicableOnStation {
            get {
                return ResourceManager.GetString("CouponNotApplicableOnStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher không tồn tại.
        /// </summary>
        internal static string CouponNotExist {
            get {
                return ResourceManager.GetString("CouponNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher không sử dụng được ở chi nhánh này.
        /// </summary>
        internal static string CouponNotHonored {
            get {
                return ResourceManager.GetString("CouponNotHonored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher không hợp lệ cho lần này.
        /// </summary>
        internal static string CouponNotValid {
            get {
                return ResourceManager.GetString("CouponNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher đã được sử dụng.
        /// </summary>
        internal static string CouponRedeemed {
            get {
                return ResourceManager.GetString("CouponRedeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gặp lỗi nghiêm trọng. Vui lòng tiến hành thu ngân để được giúp đỡ..
        /// </summary>
        internal static string CriticalErrorEncountered {
            get {
                return ResourceManager.GetString("CriticalErrorEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thành viên hiện tại không tồn tại..
        /// </summary>
        internal static string CurrentMemberTypeNotExist {
            get {
                return ResourceManager.GetString("CurrentMemberTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên hiện tại không được phép thực hiện bất kỳ hành động..
        /// </summary>
        internal static string CurrentSessionNotAllowedAnyActions {
            get {
                return ResourceManager.GetString("CurrentSessionNotAllowedAnyActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản khách hàng không đủ số dư để đăng nhập hoặc tải lại..
        /// </summary>
        internal static string CustomerAccountInsufficientBalance {
            get {
                return ResourceManager.GetString("CustomerAccountInsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản khách hàng không đủ số dư để đăng nhập hoặc tải lại..
        /// </summary>
        internal static string CustomerAccountInsufficientBalanceForLoginReload {
            get {
                return ResourceManager.GetString("CustomerAccountInsufficientBalanceForLoginReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản khách hàng không đủ số dư để tận dụng sản phẩm..
        /// </summary>
        internal static string CustomerAccountInsufficientBalanceToAvailProduct {
            get {
                return ResourceManager.GetString("CustomerAccountInsufficientBalanceToAvailProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo tài khoản khách hàng không tồn tại..
        /// </summary>
        internal static string CustomerAccountPromoNotExist {
            get {
                return ResourceManager.GetString("CustomerAccountPromoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng có một ví hiện có cho cybercafe này..
        /// </summary>
        internal static string CustomerHasExistingWallet {
            get {
                return ResourceManager.GetString("CustomerHasExistingWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng không tồn tại.
        /// </summary>
        internal static string CustomerNotExist {
            get {
                return ResourceManager.GetString("CustomerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng không có quảng cáo hiện có..
        /// </summary>
        internal static string CustomerNotHaveExistingPromo {
            get {
                return ResourceManager.GetString("CustomerNotHaveExistingPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng không phải là thành viên.
        /// </summary>
        internal static string CustomerNotMember {
            get {
                return ResourceManager.GetString("CustomerNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký sử dụng khách hàng không tồn tại.
        /// </summary>
        internal static string CustomerSessionLogNotExist {
            get {
                return ResourceManager.GetString("CustomerSessionLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thời gian đăng nhập của khách hàng không tồn tại.
        /// </summary>
        internal static string CustomerSessionNotExist {
            get {
                return ResourceManager.GetString("CustomerSessionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng đã đăng xuất thành công.
        /// </summary>
        internal static string CustomerSuccesfullyLoggedOut {
            get {
                return ResourceManager.GetString("CustomerSuccesfullyLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng này không được hỗ trợ.
        /// </summary>
        internal static string CustomerTypeNotSupported {
            get {
                return ResourceManager.GetString("CustomerTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy ví khách hàng..
        /// </summary>
        internal static string CustomerWalletNotFound {
            get {
                return ResourceManager.GetString("CustomerWalletNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Cybercafe đã được sử dụng.
        /// </summary>
        internal static string CybercafeNameTaken {
            get {
                return ResourceManager.GetString("CybercafeNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu về cybercafe không tồn tại.
        /// </summary>
        internal static string CyberCafeReferralNotExist {
            get {
                return ResourceManager.GetString("CyberCafeReferralNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng thời gian hơn 6 ngày hoặc không hợp lệ..
        /// </summary>
        internal static string DateIntervalInvalid {
            get {
                return ResourceManager.GetString("DateIntervalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đích sẽ đi qua số dư tối đa được phép..
        /// </summary>
        internal static string DestinationAccountOverMaxAllowedBalance {
            get {
                return ResourceManager.GetString("DestinationAccountOverMaxAllowedBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân chia không tồn tại..
        /// </summary>
        internal static string DivisionNotExist {
            get {
                return ResourceManager.GetString("DivisionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng yêu cầu nạp tiền không tồn tại.
        /// </summary>
        internal static string EloadTopupPartnerNotExist {
            get {
                return ResourceManager.GetString("EloadTopupPartnerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng yêu cầu nạp tiền không tồn tại.
        /// </summary>
        internal static string EloadTopupRequestNotExist {
            get {
                return ResourceManager.GetString("EloadTopupRequestNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email bạn đã nhập chưa được đăng ký..
        /// </summary>
        internal static string EmailAddressEnteredNotRegistered {
            get {
                return ResourceManager.GetString("EmailAddressEnteredNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy địa chỉ email.
        /// </summary>
        internal static string EmailAddressNotFound {
            get {
                return ResourceManager.GetString("EmailAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email là cần thiết để tận dụng tính năng này. Vui lòng cập nhật hồ sơ của bạn..
        /// </summary>
        internal static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi email đã thất bại..
        /// </summary>
        internal static string EmailDeliveryFailed {
            get {
                return ResourceManager.GetString("EmailDeliveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không hợp lệ.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không tồn tại. Vui lòng nhập một địa chỉ email làm việc..
        /// </summary>
        internal static string EmailNotExist {
            get {
                return ResourceManager.GetString("EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông số email không tồn tại..
        /// </summary>
        internal static string EmailParameterNotExist {
            get {
                return ResourceManager.GetString("EmailParameterNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một email chứa các hướng dẫn để đặt lại mật khẩu của bạn đã được gửi tới {0}..
        /// </summary>
        internal static string EmailResetPasswordInstructionSent {
            get {
                return ResourceManager.GetString("EmailResetPasswordInstructionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu email không tồn tại..
        /// </summary>
        internal static string EmailTemplateNotExist {
            get {
                return ResourceManager.GetString("EmailTemplateNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi về mặt hàng tại chi nhánh này không tồn tại.
        /// </summary>
        internal static string EndShiftBranchInventoryDetailNotExist {
            get {
                return ResourceManager.GetString("EndShiftBranchInventoryDetailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán điện tử bị vô hiệu hóa.
        /// </summary>
        internal static string EpaymentDisabled {
            get {
                return ResourceManager.GetString("EpaymentDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp dịch vụ không tồn tại.
        /// </summary>
        internal static string EpaymentProviderNotExist {
            get {
                return ResourceManager.GetString("EpaymentProviderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp dịch vụ thanh toán là vô giá trị.
        /// </summary>
        internal static string EpaymentProviderNull {
            get {
                return ResourceManager.GetString("EpaymentProviderNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi trong quá trình phân tích mẫu email..
        /// </summary>
        internal static string ErrorParsingEmailTemplate {
            get {
                return ResourceManager.GetString("ErrorParsingEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra lỗi lưu tập tin..
        /// </summary>
        internal static string ErrorSavingFile {
            get {
                return ResourceManager.GetString("ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi trong khi gửi mã yêu cầu đến địa chỉ email. Để lấy mã, vui lòng kiểm tra lịch sử giao dịch..
        /// </summary>
        internal static string ErrorSendingClaimCode {
            get {
                return ResourceManager.GetString("ErrorSendingClaimCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi gửi liên kết đặt lại mật khẩu đến email của bạn. Vui lòng thử lại sau..
        /// </summary>
        internal static string ErrorSendingPasswordResetLink {
            get {
                return ResourceManager.GetString("ErrorSendingPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh từ giao dịch không tồn tại nữa. Hệ thống không thể tiến hành hủy bỏ..
        /// </summary>
        internal static string ErrorVoidingBranchTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingBranchTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty từ giao dịch không tồn tại nữa. Hệ thống không thể tiến hành hủy bỏ..
        /// </summary>
        internal static string ErrorVoidingCompanyTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingCompanyTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản khách hàng từ giao dịch không tồn tại nữa. Hệ thống không thể tiến hành hủy bỏ..
        /// </summary>
        internal static string ErrorVoidingCustomerAccountTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingCustomerAccountTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách từ giao dịch không tồn tại nữa. Hệ thống không thể tiến hành hủy bỏ..
        /// </summary>
        internal static string ErrorVoidingGuestTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingGuestTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các thành viên từ giao dịch không tồn tại nữa. Hệ thống không thể tiến hành hủy bỏ..
        /// </summary>
        internal static string ErrorVoidingMemberTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingMemberTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệnh bán hàng từ giao dịch không còn tồn tại nữa. Hệ thống không thể tiến hành hủy bỏ..
        /// </summary>
        internal static string ErrorVoidingSalesOrderTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingSalesOrderTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Eshop đã nhập vượt quá độ dài tối đa cho phép là 50 ký tự..
        /// </summary>
        internal static string EShopCodeExceedMaxLength {
            get {
                return ResourceManager.GetString("EShopCodeExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh EShop không tồn tại..
        /// </summary>
        internal static string EShopPictureNotExist {
            get {
                return ResourceManager.GetString("EShopPictureNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi thường gặp không tồn tại.
        /// </summary>
        internal static string FAQNotExist {
            get {
                return ResourceManager.GetString("FAQNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép sử dụng tính năng này..
        /// </summary>
        internal static string FeatureNotAllowed {
            get {
                return ResourceManager.GetString("FeatureNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng này chỉ dành cho các thành viên không gian mạng..
        /// </summary>
        internal static string FeatureOnlyAvailableToCybercafeMembers {
            get {
                return ResourceManager.GetString("FeatureOnlyAvailableToCybercafeMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường có giá trị trống.
        /// </summary>
        internal static string FieldEmpty {
            get {
                return ResourceManager.GetString("FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tệp chỉ có thể được tải lên một lần cho mỗi công ty..
        /// </summary>
        internal static string FilenameCanOnlyBeUploadedOnce {
            get {
                return ResourceManager.GetString("FilenameCanOnlyBeUploadedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước tệp vượt quá {0} byte..
        /// </summary>
        internal static string FileSizeExceeded {
            get {
                return ResourceManager.GetString("FileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khấu trừ hoàn toàn Thời gian phát sóng không tồn tại..
        /// </summary>
        internal static string FullDeductionAirtimeNotExist {
            get {
                return ResourceManager.GetString("FullDeductionAirtimeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm không tồn tại..
        /// </summary>
        internal static string GroupNotExist {
            get {
                return ResourceManager.GetString("GroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tiến hành. Tài khoản khách đã hết hạn..
        /// </summary>
        internal static string GuestAccountAlreadyExpired {
            get {
                return ResourceManager.GetString("GuestAccountAlreadyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian phát sóng của khách không tồn tại..
        /// </summary>
        internal static string GuestAirtimeNotExist {
            get {
                return ResourceManager.GetString("GuestAirtimeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách không được phép đăng nhập vào chi nhánh được chỉ định..
        /// </summary>
        internal static string GuestNotAllowedToLogin {
            get {
                return ResourceManager.GetString("GuestNotAllowedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách không tồn tại.
        /// </summary>
        internal static string GuestNotExist {
            get {
                return ResourceManager.GetString("GuestNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sạc không chính xác được tìm thấy trong phiên khách hàng..
        /// </summary>
        internal static string IncorrectChargingType {
            get {
                return ResourceManager.GetString("IncorrectChargingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng / mật khẩu không chính xác..
        /// </summary>
        internal static string IncorrectUsernamePassword {
            get {
                return ResourceManager.GetString("IncorrectUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ hàng có sẵn trong kho..
        /// </summary>
        internal static string InsufficientAvailableStockInventory {
            get {
                return ResourceManager.GetString("InsufficientAvailableStockInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có một số dư không đủ..
        /// </summary>
        internal static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư khách không đủ. Khách có thể đã sử dụng số tiền..
        /// </summary>
        internal static string InsufficientGuestBalance {
            get {
                return ResourceManager.GetString("InsufficientGuestBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thực hiện hành động ghi nợ. Điểm trung thành không đủ..
        /// </summary>
        internal static string InsufficientLoyaltyPoints {
            get {
                return ResourceManager.GetString("InsufficientLoyaltyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán không đầy đủ. Giá khuyến mãi là {0}..
        /// </summary>
        internal static string InsufficientPayment {
            get {
                return ResourceManager.GetString("InsufficientPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng toupup không đủ. Phí thành viên là {0}..
        /// </summary>
        internal static string InsufficientTopupAmount {
            get {
                return ResourceManager.GetString("InsufficientTopupAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi máy chủ nội bộ.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi máy chủ nội bộ.
        /// </summary>
        internal static string InternalServerError1 {
            get {
                return ResourceManager.GetString("InternalServerError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca làm việc thu ngân không hợp lệ.
        /// </summary>
        internal static string InvalidCashierSession {
            get {
                return ResourceManager.GetString("InvalidCashierSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng email không hợp lệ..
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị trường không hợp lệ..
        /// </summary>
        internal static string InvalidFieldValue {
            get {
                return ResourceManager.GetString("InvalidFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng hình ảnh không hợp lệ..
        /// </summary>
        internal static string InvalidImageFormat {
            get {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng địa chỉ IP không hợp lệ..
        /// </summary>
        internal static string InvalidIPAddressFormat {
            get {
                return ResourceManager.GetString("InvalidIPAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập không hợp lệ..
        /// </summary>
        internal static string InvalidLoginCredentials {
            get {
                return ResourceManager.GetString("InvalidLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng địa chỉ MAC không hợp lệ..
        /// </summary>
        internal static string InvalidMACAddressFormat {
            get {
                return ResourceManager.GetString("InvalidMACAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang không hợp lệ..
        /// </summary>
        internal static string InvalidPageNumber {
            get {
                return ResourceManager.GetString("InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thông báo đặt lại mật khẩu không hợp lệ..
        /// </summary>
        internal static string InvalidPasswordResetToken {
            get {
                return ResourceManager.GetString("InvalidPasswordResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thanh toán không hợp lệ..
        /// </summary>
        internal static string InvalidPaymentType {
            get {
                return ResourceManager.GetString("InvalidPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài tên PC không hợp lệ..
        /// </summary>
        internal static string InvalidPCNameLength {
            get {
                return ResourceManager.GetString("InvalidPCNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp PDF không hợp lệ..
        /// </summary>
        internal static string InvalidPDFFile {
            get {
                return ResourceManager.GetString("InvalidPDFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đổi quà không hợp lệ..
        /// </summary>
        internal static string InvalidRedemptionCode {
            get {
                return ResourceManager.GetString("InvalidRedemptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên không hợp lệ..
        /// </summary>
        internal static string InvalidSession {
            get {
                return ResourceManager.GetString("InvalidSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã trạng thái không hợp lệ..
        /// </summary>
        internal static string InvalidStatusCode {
            get {
                return ResourceManager.GetString("InvalidStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thông báo chuyển không hợp lệ..
        /// </summary>
        internal static string InvalidTransferToken {
            get {
                return ResourceManager.GetString("InvalidTransferToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục này không có sẵn để mua lại..
        /// </summary>
        internal static string ItemNotAvailableForRedemption {
            get {
                return ResourceManager.GetString("ItemNotAvailableForRedemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa là null..
        /// </summary>
        internal static string KeyNull {
            get {
                return ResourceManager.GetString("KeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bản quyền không hợp lệ.
        /// </summary>
        internal static string LicenseKeyInvalid {
            get {
                return ResourceManager.GetString("LicenseKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đăng xuất..
        /// </summary>
        internal static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép đăng nhập vào chi nhánh này..
        /// </summary>
        internal static string LoginNotAllowed {
            get {
                return ResourceManager.GetString("LoginNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát ra thành công..
        /// </summary>
        internal static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ MAC: {0} đã được sử dụng trong nhánh {1}.
        /// </summary>
        internal static string MACAddressAlreadyInUse {
            get {
                return ResourceManager.GetString("MACAddressAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ MAC {0} được sử dụng bởi nhiều máy thu ngân.
        /// </summary>
        internal static string MACAddressUsedByMultipleCashierStation {
            get {
                return ResourceManager.GetString("MACAddressUsedByMultipleCashierStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền nạp tiền đã vượt quá số tiền nạp tối đa của cybercafe..
        /// </summary>
        internal static string MaxTopupAmountExceeded {
            get {
                return ResourceManager.GetString("MaxTopupAmountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt số tiền nạp tối đa chưa được xác định cho an ninh mạng này..
        /// </summary>
        internal static string MaxTopupAmountNotDefined {
            get {
                return ResourceManager.GetString("MaxTopupAmountNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị đo lường không tồn tại..
        /// </summary>
        internal static string MeasurementUnitNotExist {
            get {
                return ResourceManager.GetString("MeasurementUnitNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên Airtime không tồn tại..
        /// </summary>
        internal static string MemberAirtimeNotExist {
            get {
                return ResourceManager.GetString("MemberAirtimeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên đã chấp nhận tnc!.
        /// </summary>
        internal static string MemberAlreadyAcceptedTNC {
            get {
                return ResourceManager.GetString("MemberAlreadyAcceptedTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email thành viên không được xác minh..
        /// </summary>
        internal static string MemberEmailNotVerified {
            get {
                return ResourceManager.GetString("MemberEmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ thành viên chơi không tìm thấy..
        /// </summary>
        internal static string MemberHoursPlayedNotFound {
            get {
                return ResourceManager.GetString("MemberHoursPlayedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký thành viên không tồn tại..
        /// </summary>
        internal static string MemberLoyaltyLogNotExist {
            get {
                return ResourceManager.GetString("MemberLoyaltyLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên trung thành không tồn tại..
        /// </summary>
        internal static string MemberLoyaltyNotExist {
            get {
                return ResourceManager.GetString("MemberLoyaltyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên không tồn tại..
        /// </summary>
        internal static string MemberNotExist {
            get {
                return ResourceManager.GetString("MemberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên chưa có email đăng ký..
        /// </summary>
        internal static string MemberNotHaveRegisteredEmail {
            get {
                return ResourceManager.GetString("MemberNotHaveRegisteredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên chưa được đăng ký với an ninh mạng này. Vui lòng nạp.
        /// </summary>
        internal static string MemberNotYetEnrolled {
            get {
                return ResourceManager.GetString("MemberNotYetEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp di chuyển không tồn tại..
        /// </summary>
        internal static string MigratedFileNotExist {
            get {
                return ResourceManager.GetString("MigratedFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên di cư không tồn tại..
        /// </summary>
        internal static string MigratedMemberNotExist {
            get {
                return ResourceManager.GetString("MigratedMemberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu dữ liệu trên mỗi trang hoặc trang Không có trường..
        /// </summary>
        internal static string MissingDataPerPage {
            get {
                return ResourceManager.GetString("MissingDataPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới và xác nhận mật khẩu mới không khớp..
        /// </summary>
        internal static string NewPasswordConfirmNewPasswordNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordConfirmNewPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới phải khác với mật khẩu cũ..
        /// </summary>
        internal static string NewPasswordMatchOldPassword {
            get {
                return ResourceManager.GetString("NewPasswordMatchOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thời gian phát sóng còn lại..
        /// </summary>
        internal static string NoAirtimeRemaining {
            get {
                return ResourceManager.GetString("NoAirtimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher này không có sẵn.
        /// </summary>
        internal static string NoCouponAvailable {
            get {
                return ResourceManager.GetString("NoCouponAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thêm mã có sẵn cho loại mã và mệnh giá được chọn..
        /// </summary>
        internal static string NoMoreCodesAvailable {
            get {
                return ResourceManager.GetString("NoMoreCodesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không tồn tại. Vui lòng nhập một địa chỉ email làm việc..
        /// </summary>
        internal static string NonExistingEmail {
            get {
                return ResourceManager.GetString("NonExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad không tồn tại..
        /// </summary>
        internal static string NotepadNotExist {
            get {
                return ResourceManager.GetString("NotepadNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đồng ý.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không chính xác.
        /// </summary>
        internal static string OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng đã được chấp nhận..
        /// </summary>
        internal static string OrderAlreadyAccepted {
            get {
                return ResourceManager.GetString("OrderAlreadyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký chi phí khác không tồn tại..
        /// </summary>
        internal static string OtherExpenseLogNotExist {
            get {
                return ResourceManager.GetString("OtherExpenseLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã hết hàng..
        /// </summary>
        internal static string OutOfStock {
            get {
                return ResourceManager.GetString("OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được thay đổi thành công..
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC này chưa được cấu hình đúng. Vui lòng liên hệ với thủ quỹ để được hỗ trợ..
        /// </summary>
        internal static string PCNotProperlyConfigured {
            get {
                return ResourceManager.GetString("PCNotProperlyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệnh chờ không tồn tại..
        /// </summary>
        internal static string PendingOrderNotExist {
            get {
                return ResourceManager.GetString("PendingOrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại hợp lệ.
        /// </summary>
        internal static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một vấn đề đã gặp phải trong khi xử lý yêu cầu của bạn. Vui lòng liên hệ với quản trị viên..
        /// </summary>
        internal static string ProblemEncounteredWhileProcessingRequest {
            get {
                return ResourceManager.GetString("ProblemEncounteredWhileProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có vấn đề với dữ liệu đã cho..
        /// </summary>
        internal static string ProblemGivenData {
            get {
                return ResourceManager.GetString("ProblemGivenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id sản phẩm {0} không có sẵn trong kho của chi nhánh..
        /// </summary>
        internal static string ProductIDNotAvailable {
            get {
                return ResourceManager.GetString("ProductIDNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm không tồn tại..
        /// </summary>
        internal static string ProductNotExist {
            get {
                return ResourceManager.GetString("ProductNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể hủy bỏ quảng cáo vì nó đã được sử dụng..
        /// </summary>
        internal static string PromoAlreadyUsedCantCancel {
            get {
                return ResourceManager.GetString("PromoAlreadyUsedCantCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vẫn có một quảng cáo trong sử dụng. Mua hàng đã bị từ chối..
        /// </summary>
        internal static string PromoInUsePurchaseRejected {
            get {
                return ResourceManager.GetString("PromoInUsePurchaseRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo không áp dụng cho loại khách hàng này..
        /// </summary>
        internal static string PromoNotApplicableForCustomerType {
            get {
                return ResourceManager.GetString("PromoNotApplicableForCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo chưa kết thúc vì không có nhân viên thu ngân..
        /// </summary>
        internal static string PromoNotEndedCashierNotAvailable {
            get {
                return ResourceManager.GetString("PromoNotEndedCashierNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo không kết hợp..
        /// </summary>
        internal static string PromoNotExist {
            get {
                return ResourceManager.GetString("PromoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo đã được hoàn trả thành công..
        /// </summary>
        internal static string PromoRefundedSuccesfully {
            get {
                return ResourceManager.GetString("PromoRefundedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký giao dịch quảng cáo không tồn tại..
        /// </summary>
        internal static string PromoTransactionLogNotExist {
            get {
                return ResourceManager.GetString("PromoTransactionLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại quảng cáo không được hỗ trợ..
        /// </summary>
        internal static string PromoTypeNotSupported {
            get {
                return ResourceManager.GetString("PromoTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng cung cấp ngày hết hạn sau ngày hôm nay..
        /// </summary>
        internal static string ProvideExpirationDate {
            get {
                return ResourceManager.GetString("ProvideExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng không nên là 0..
        /// </summary>
        internal static string QuantityZero {
            get {
                return ResourceManager.GetString("QuantityZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi đã tồn tại..
        /// </summary>
        internal static string QuestionAlreadyExist {
            get {
                return ResourceManager.GetString("QuestionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ không được cấu hình cho loại trạm này..
        /// </summary>
        internal static string RateNotConfigured {
            get {
                return ResourceManager.GetString("RateNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá không tồn tại.
        /// </summary>
        internal static string RateNotExist {
            get {
                return ResourceManager.GetString("RateNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do phải ít hơn {0} ký tự..
        /// </summary>
        internal static string ReasonMaxLength {
            get {
                return ResourceManager.GetString("ReasonMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vùng không tồn tại..
        /// </summary>
        internal static string RegionNotExist {
            get {
                return ResourceManager.GetString("RegionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do từ chối là cần thiết..
        /// </summary>
        internal static string RejectionReasonRequired {
            get {
                return ResourceManager.GetString("RejectionReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu bị từ chối..
        /// </summary>
        internal static string RequestDenied {
            get {
                return ResourceManager.GetString("RequestDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên yêu cầu không sở hữu mã này..
        /// </summary>
        internal static string RequestingMemberNotOwnCode {
            get {
                return ResourceManager.GetString("RequestingMemberNotOwnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm yêu cầu không bằng máy chủ..
        /// </summary>
        internal static string RequiredPointsNotEqualToServer {
            get {
                return ResourceManager.GetString("RequiredPointsNotEqualToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id bán lẻ {0} không được bán tại chi nhánh: {1}..
        /// </summary>
        internal static string RetailIDNotForSale {
            get {
                return ResourceManager.GetString("RetailIDNotForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán lẻ không tồn tại..
        /// </summary>
        internal static string RetailNotExist {
            get {
                return ResourceManager.GetString("RetailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều chỉnh bán hàng không tồn tại..
        /// </summary>
        internal static string SalesAdjustmentNotExist {
            get {
                return ResourceManager.GetString("SalesAdjustmentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệnh bán hàng không tồn tại..
        /// </summary>
        internal static string SalesOrderNotExist {
            get {
                return ResourceManager.GetString("SalesOrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesRetail không tồn tại..
        /// </summary>
        internal static string SalesRetailNotExist {
            get {
                return ResourceManager.GetString("SalesRetailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin được chọn không phải là một hình ảnh..
        /// </summary>
        internal static string SelectedFileNotImage {
            get {
                return ResourceManager.GetString("SelectedFileNotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên này đã được thay thế..
        /// </summary>
        internal static string SessionAlreadyReplaced {
            get {
                return ResourceManager.GetString("SessionAlreadyReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên không tồn tại..
        /// </summary>
        internal static string SessionNotExist {
            get {
                return ResourceManager.GetString("SessionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca làm việc của bạn đã kết thúc.
        /// </summary>
        internal static string ShiftAlreadyEnded {
            get {
                return ResourceManager.GetString("ShiftAlreadyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết thay đổi này không tồn tại.
        /// </summary>
        internal static string ShiftDetailNotExist {
            get {
                return ResourceManager.GetString("ShiftDetailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự thay đổi này không tồn tại.
        /// </summary>
        internal static string ShiftNotExist {
            get {
                return ResourceManager.GetString("ShiftNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh cửa hàng không tồn tại..
        /// </summary>
        internal static string ShopPictureNotExist {
            get {
                return ResourceManager.GetString("ShopPictureNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký giao dịch cửa hàng không tồn tại.
        /// </summary>
        internal static string ShopTransactionLogNotExist {
            get {
                return ResourceManager.GetString("ShopTransactionLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên bản phần mềm không tồn tại..
        /// </summary>
        internal static string SoftwareVersionNotExist {
            get {
                return ResourceManager.GetString("SoftwareVersionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chênh lệch giữa Ngày bắt đầu và Ngày kết thúc không được lớn hơn 7 ngày..
        /// </summary>
        internal static string StartDateEndDateDifferenceGreaterThan7Days {
            get {
                return ResourceManager.GetString("StartDateEndDateDifferenceGreaterThan7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu không thể lớn hơn Ngày kết thúc.
        /// </summary>
        internal static string StartDateGreaterThanEndDate {
            get {
                return ResourceManager.GetString("StartDateGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm có địa chỉ IP {0} cho Chi nhánh {1} của Công ty {2} đã tồn tại..
        /// </summary>
        internal static string StationIPAlreadyExist {
            get {
                return ResourceManager.GetString("StationIPAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm có tên &quot;+ {0} +&quot; cho Chi nhánh &quot;+ {1} +&quot; của Công ty &quot;+ {2} +&quot; đã tồn tại..
        /// </summary>
        internal static string StationNameAlreadyExist {
            get {
                return ResourceManager.GetString("StationNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm không tồn tại..
        /// </summary>
        internal static string StationNotExist {
            get {
                return ResourceManager.GetString("StationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trạm không được cấu hình cho loại trạm này và loại thành viên..
        /// </summary>
        internal static string StationRateNotConfigured {
            get {
                return ResourceManager.GetString("StationRateNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký trạm thành công..
        /// </summary>
        internal static string StationRegistrationSuccesful {
            get {
                return ResourceManager.GetString("StationRegistrationSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang đăng nhập vào một PC khác trên {0} - {1}.
        /// </summary>
        internal static string StillLoggedIn {
            get {
                return ResourceManager.GetString("StillLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vẫn đang đăng nhập trên một máy tính khác..
        /// </summary>
        internal static string StillLoggedIn1 {
            get {
                return ResourceManager.GetString("StillLoggedIn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ chi tiết liên lạc không tồn tại..
        /// </summary>
        internal static string SupportContactDetailNotExist {
            get {
                return ResourceManager.GetString("SupportContactDetailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình hệ thống không tồn tại..
        /// </summary>
        internal static string SystemConfigurationNotExist {
            get {
                return ResourceManager.GetString("SystemConfigurationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỹ thuật viên không được phép đăng nhập vào chi nhánh được chỉ định.
        /// </summary>
        internal static string TechnicianNotAllowedToLogin {
            get {
                return ResourceManager.GetString("TechnicianNotAllowedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỹ thuật viên không tồn tại.
        /// </summary>
        internal static string TechnicianNotExist {
            get {
                return ResourceManager.GetString("TechnicianNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khoản và Điều kiện không tồn tại..
        /// </summary>
        internal static string TNCNotExist {
            get {
                return ResourceManager.GetString("TNCNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền nạp không đủ. Phí thành viên là {0} và giá khuyến mãi là {1}..
        /// </summary>
        internal static string TopupAmountInsufficient {
            get {
                return ResourceManager.GetString("TopupAmountInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch này đã có một yêu cầu điều chỉnh đang chờ xử lý..
        /// </summary>
        internal static string TransactionAlreadyHasPendingAdjustmentRequest {
            get {
                return ResourceManager.GetString("TransactionAlreadyHasPendingAdjustmentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch này đã bị hủy..
        /// </summary>
        internal static string TransactionAlreadyVoided {
            get {
                return ResourceManager.GetString("TransactionAlreadyVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký giao dịch không tồn tại.
        /// </summary>
        internal static string TransactionLogNotExist {
            get {
                return ResourceManager.GetString("TransactionLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký giao dịch không thuộc sở hữu của người dùng..
        /// </summary>
        internal static string TransactionLogNotOwned {
            get {
                return ResourceManager.GetString("TransactionLogNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển mã thông báo đã hết hạn..
        /// </summary>
        internal static string TransferTokenExpired {
            get {
                return ResourceManager.GetString("TransferTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi mã thông báo không hợp lệ.
        /// </summary>
        internal static string TransferTokenNotExist {
            get {
                return ResourceManager.GetString("TransferTokenNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể liên lạc với máy chủ phụ trợ. Vui lòng tiến hành thu ngân để được giúp đỡ..
        /// </summary>
        internal static string UnableToCommunicateToBackend {
            get {
                return ResourceManager.GetString("UnableToCommunicateToBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản người dùng bị vô hiệu hóa..
        /// </summary>
        internal static string UserAccountDeactivated {
            get {
                return ResourceManager.GetString("UserAccountDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng không tồn tại.
        /// </summary>
        internal static string UserGroupNotExist {
            get {
                return ResourceManager.GetString("UserGroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên này đã có người dùng..
        /// </summary>
        internal static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không tồn tại..
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên của người dùng từ trạm đã được gỡ bỏ thành công..
        /// </summary>
        internal static string UserSessionRemoved {
            get {
                return ResourceManager.GetString("UserSessionRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ô trống đã bị vô hiệu hóa cho thương gia này.
        /// </summary>
        internal static string VoidingDisbaled {
            get {
                return ResourceManager.GetString("VoidingDisbaled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép làm mất hiệu lực giao dịch này..
        /// </summary>
        internal static string VoidTransactionNotAllowed {
            get {
                return ResourceManager.GetString("VoidTransactionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi ví đã gặp phải..
        /// </summary>
        internal static string WalletError {
            get {
                return ResourceManager.GetString("WalletError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký giao dịch ví không tồn tại..
        /// </summary>
        internal static string WalletTransactionNotExist {
            get {
                return ResourceManager.GetString("WalletTransactionNotExist", resourceCulture);
            }
        }
    }
}
