//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dts_shared.ResponseMessageResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dts_shared.ResponseMessageResource.ErrorMessageResource", typeof(ErrorMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us does not exist..
        /// </summary>
        internal static string AboutUsNotExist {
            get {
                return ResourceManager.GetString("AboutUsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is currently deactivated..
        /// </summary>
        internal static string AccountDeactivated {
            get {
                return ResourceManager.GetString("AccountDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has expired..
        /// </summary>
        internal static string AccountExpired {
            get {
                return ResourceManager.GetString("AccountExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has no balance for this cybercafe. Please go to the cashier to do your first topup..
        /// </summary>
        internal static string AccountHasNoBalance {
            get {
                return ResourceManager.GetString("AccountHasNoBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add products from your inventory..
        /// </summary>
        internal static string AddProductsFromInventory {
            get {
                return ResourceManager.GetString("AddProductsFromInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Order does not exist..
        /// </summary>
        internal static string AdjustmentOrderNotExist {
            get {
                return ResourceManager.GetString("AdjustmentOrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Product does not exist..
        /// </summary>
        internal static string AdjustmentProductNotExist {
            get {
                return ResourceManager.GetString("AdjustmentProductNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount given is not equal to the promo price..
        /// </summary>
        internal static string AmountGivenNotEqualToPromoPrice {
            get {
                return ResourceManager.GetString("AmountGivenNotEqualToPromoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should not be zero or negative..
        /// </summary>
        internal static string AmountZeroOrNegative {
            get {
                return ResourceManager.GetString("AmountZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval code is null or blank..
        /// </summary>
        internal static string ApprovalCodeEmpty {
            get {
                return ResourceManager.GetString("ApprovalCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Load Wallet does not exist..
        /// </summary>
        internal static string BonusLoadWalletNotExist {
            get {
                return ResourceManager.GetString("BonusLoadWalletNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch already exists for the cybercafe..
        /// </summary>
        internal static string BranchAlreadyExist {
            get {
                return ResourceManager.GetString("BranchAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch from the transaction log and the sales order does not match..
        /// </summary>
        internal static string BranchAndSalesOrderNotMatch {
            get {
                return ResourceManager.GetString("BranchAndSalesOrderNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Balance does not exist..
        /// </summary>
        internal static string BranchBalanceNotExist {
            get {
                return ResourceManager.GetString("BranchBalanceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Configuration does not exist..
        /// </summary>
        internal static string BranchConfigurationNotExist {
            get {
                return ResourceManager.GetString("BranchConfigurationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is currently deactivated for this branch..
        /// </summary>
        internal static string BranchFeatureDeactivated {
            get {
                return ResourceManager.GetString("BranchFeatureDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Group does not exist..
        /// </summary>
        internal static string BranchGroupNotExist {
            get {
                return ResourceManager.GetString("BranchGroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch ID and CCBoot Mac Address cannot be null at the same time..
        /// </summary>
        internal static string BranchIDAndMacAddressNull {
            get {
                return ResourceManager.GetString("BranchIDAndMacAddressNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch has insufficient balance..
        /// </summary>
        internal static string BranchInsufficientBalance {
            get {
                return ResourceManager.GetString("BranchInsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Inventory does not exist..
        /// </summary>
        internal static string BranchInventoryNotExist {
            get {
                return ResourceManager.GetString("BranchInventoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch does not exist..
        /// </summary>
        internal static string BranchNotExist {
            get {
                return ResourceManager.GetString("BranchNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Retail Pricing does not exist..
        /// </summary>
        internal static string BranchRetailPricingNotExist {
            get {
                return ResourceManager.GetString("BranchRetailPricingNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch version not found..
        /// </summary>
        internal static string BranchVersionNotFound {
            get {
                return ResourceManager.GetString("BranchVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffet Airtime does not exist..
        /// </summary>
        internal static string BuffetAirtimeNotExist {
            get {
                return ResourceManager.GetString("BuffetAirtimeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reject sales order from different branch..
        /// </summary>
        internal static string CannoRejectSalesOrderFromDifferentBranch {
            get {
                return ResourceManager.GetString("CannoRejectSalesOrderFromDifferentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot accept sales order from a different branch..
        /// </summary>
        internal static string CannotAcceptSalesOrderFromDifferentBranch {
            get {
                return ResourceManager.GetString("CannotAcceptSalesOrderFromDifferentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add order with empty sales retail..
        /// </summary>
        internal static string CannotAddOrderEmptySalesRetail {
            get {
                return ResourceManager.GetString("CannotAddOrderEmptySalesRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process a non-pending inventory adjustment order..
        /// </summary>
        internal static string CannotProcessNonPendingInventoryAdjustmentOrder {
            get {
                return ResourceManager.GetString("CannotProcessNonPendingInventoryAdjustmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process a non-pending sales adjustment order..
        /// </summary>
        internal static string CannotProcessNonPendingSalesAdjustmentOrder {
            get {
                return ResourceManager.GetString("CannotProcessNonPendingSalesAdjustmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier Group does not exist..
        /// </summary>
        internal static string CashierGroupNotExist {
            get {
                return ResourceManager.GetString("CashierGroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier Group Permission does not exist..
        /// </summary>
        internal static string CashierGroupPermissionNotExist {
            get {
                return ResourceManager.GetString("CashierGroupPermissionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier does not exist..
        /// </summary>
        internal static string CashierNotExist {
            get {
                return ResourceManager.GetString("CashierNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cashier is not yet registered..
        /// </summary>
        internal static string CashierNotRegistered {
            get {
                return ResourceManager.GetString("CashierNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier Session Log does not exist..
        /// </summary>
        internal static string CashierSessionLogNotExist {
            get {
                return ResourceManager.GetString("CashierSessionLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier Session does not exist..
        /// </summary>
        internal static string CashierSessionNotExist {
            get {
                return ResourceManager.GetString("CashierSessionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier has not ended a shift yet..
        /// </summary>
        internal static string CashierShiftNotEnded {
            get {
                return ResourceManager.GetString("CashierShiftNotEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier Station does not exist..
        /// </summary>
        internal static string CashierStationNotExist {
            get {
                return ResourceManager.GetString("CashierStationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City does not exist..
        /// </summary>
        internal static string CityNotExist {
            get {
                return ResourceManager.GetString("CityNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Loyalty Log does not exist.
        /// </summary>
        internal static string ClientLoyaltyLogNotExist {
            get {
                return ResourceManager.GetString("ClientLoyaltyLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client&apos;s session has expired..
        /// </summary>
        internal static string ClientSessionExpired {
            get {
                return ResourceManager.GetString("ClientSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following code(s) already exist(s) on the system:.
        /// </summary>
        internal static string CodeAlreadyExist {
            get {
                return ResourceManager.GetString("CodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a code that has already been used..
        /// </summary>
        internal static string CodeAlreadyUsedCantDelete {
            get {
                return ResourceManager.GetString("CodeAlreadyUsedCantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple occurences of the following code(s):.
        /// </summary>
        internal static string CodeMultipleOccurence {
            get {
                return ResourceManager.GetString("CodeMultipleOccurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code does not exist..
        /// </summary>
        internal static string CodeNotExist {
            get {
                return ResourceManager.GetString("CodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Type name already exists..
        /// </summary>
        internal static string CodeTypeNameAlreadyExist {
            get {
                return ResourceManager.GetString("CodeTypeNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Type does not exist.
        /// </summary>
        internal static string CodeTypeNotExist {
            get {
                return ResourceManager.GetString("CodeTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Configuration does not exist..
        /// </summary>
        internal static string CompanyConfigurationNotExist {
            get {
                return ResourceManager.GetString("CompanyConfigurationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Member Type Setup does not exist..
        /// </summary>
        internal static string CompanyMemberTypeNotExist {
            get {
                return ResourceManager.GetString("CompanyMemberTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company member type setup is not configured..
        /// </summary>
        internal static string CompanyMemberTypeSetupNotConfigured {
            get {
                return ResourceManager.GetString("CompanyMemberTypeSetupNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company does not exist..
        /// </summary>
        internal static string CompanyNotExist {
            get {
                return ResourceManager.GetString("CompanyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite product component does not exist..
        /// </summary>
        internal static string CompositeProductComponentNotExist {
            get {
                return ResourceManager.GetString("CompositeProductComponentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite product does not exist..
        /// </summary>
        internal static string CompositeProductNotExist {
            get {
                return ResourceManager.GetString("CompositeProductNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country does not exist..
        /// </summary>
        internal static string CountryNotExist {
            get {
                return ResourceManager.GetString("CountryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon has already expired..
        /// </summary>
        internal static string CouponAlreadyExpired {
            get {
                return ResourceManager.GetString("CouponAlreadyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You still have a coupon in use. Purchase has been rejected..
        /// </summary>
        internal static string CouponInUsePurchaseRejected {
            get {
                return ResourceManager.GetString("CouponInUsePurchaseRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coupon you are about to use is not applicable for this station type..
        /// </summary>
        internal static string CouponNotApplicableOnStation {
            get {
                return ResourceManager.GetString("CouponNotApplicableOnStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon does not exist..
        /// </summary>
        internal static string CouponNotExist {
            get {
                return ResourceManager.GetString("CouponNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon is not honored by this branch..
        /// </summary>
        internal static string CouponNotHonored {
            get {
                return ResourceManager.GetString("CouponNotHonored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon is not valid for this station type..
        /// </summary>
        internal static string CouponNotValid {
            get {
                return ResourceManager.GetString("CouponNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon has already been redeemed..
        /// </summary>
        internal static string CouponRedeemed {
            get {
                return ResourceManager.GetString("CouponRedeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error encountered. Please proceed to the cashier for help..
        /// </summary>
        internal static string CriticalErrorEncountered {
            get {
                return ResourceManager.GetString("CriticalErrorEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Member Type does not exist..
        /// </summary>
        internal static string CurrentMemberTypeNotExist {
            get {
                return ResourceManager.GetString("CurrentMemberTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current session is not allowed to perform any actions..
        /// </summary>
        internal static string CurrentSessionNotAllowedAnyActions {
            get {
                return ResourceManager.GetString("CurrentSessionNotAllowedAnyActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer account has insufficient balance for login or reload..
        /// </summary>
        internal static string CustomerAccountInsufficientBalance {
            get {
                return ResourceManager.GetString("CustomerAccountInsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer account has insufficient balance for login or reload..
        /// </summary>
        internal static string CustomerAccountInsufficientBalanceForLoginReload {
            get {
                return ResourceManager.GetString("CustomerAccountInsufficientBalanceForLoginReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer account has insufficient balance to avail product..
        /// </summary>
        internal static string CustomerAccountInsufficientBalanceToAvailProduct {
            get {
                return ResourceManager.GetString("CustomerAccountInsufficientBalanceToAvailProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Account Promo does not exist..
        /// </summary>
        internal static string CustomerAccountPromoNotExist {
            get {
                return ResourceManager.GetString("CustomerAccountPromoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer has an existing wallet for this cybercafe..
        /// </summary>
        internal static string CustomerHasExistingWallet {
            get {
                return ResourceManager.GetString("CustomerHasExistingWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer does not exist..
        /// </summary>
        internal static string CustomerNotExist {
            get {
                return ResourceManager.GetString("CustomerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer does not have an existing promo..
        /// </summary>
        internal static string CustomerNotHaveExistingPromo {
            get {
                return ResourceManager.GetString("CustomerNotHaveExistingPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is not a member..
        /// </summary>
        internal static string CustomerNotMember {
            get {
                return ResourceManager.GetString("CustomerNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Session Log does not exist..
        /// </summary>
        internal static string CustomerSessionLogNotExist {
            get {
                return ResourceManager.GetString("CustomerSessionLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Session does not exist..
        /// </summary>
        internal static string CustomerSessionNotExist {
            get {
                return ResourceManager.GetString("CustomerSessionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer has successfully logged out..
        /// </summary>
        internal static string CustomerSuccesfullyLoggedOut {
            get {
                return ResourceManager.GetString("CustomerSuccesfullyLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type is not supported..
        /// </summary>
        internal static string CustomerTypeNotSupported {
            get {
                return ResourceManager.GetString("CustomerTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer wallet not found..
        /// </summary>
        internal static string CustomerWalletNotFound {
            get {
                return ResourceManager.GetString("CustomerWalletNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cybercafe name is already taken..
        /// </summary>
        internal static string CybercafeNameTaken {
            get {
                return ResourceManager.GetString("CybercafeNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyber Cafe Referral does not exist..
        /// </summary>
        internal static string CyberCafeReferralNotExist {
            get {
                return ResourceManager.GetString("CyberCafeReferralNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date interval is more than 6 days or invalid..
        /// </summary>
        internal static string DateIntervalInvalid {
            get {
                return ResourceManager.GetString("DateIntervalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination account will go over the maximum allowed balance..
        /// </summary>
        internal static string DestinationAccountOverMaxAllowedBalance {
            get {
                return ResourceManager.GetString("DestinationAccountOverMaxAllowedBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division does not exist..
        /// </summary>
        internal static string DivisionNotExist {
            get {
                return ResourceManager.GetString("DivisionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eload Topup Partner does not exist..
        /// </summary>
        internal static string EloadTopupPartnerNotExist {
            get {
                return ResourceManager.GetString("EloadTopupPartnerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eload Topup Request does not exist..
        /// </summary>
        internal static string EloadTopupRequestNotExist {
            get {
                return ResourceManager.GetString("EloadTopupRequestNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address you entered is not yet registered..
        /// </summary>
        internal static string EmailAddressEnteredNotRegistered {
            get {
                return ResourceManager.GetString("EmailAddressEnteredNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not found..
        /// </summary>
        internal static string EmailAddressNotFound {
            get {
                return ResourceManager.GetString("EmailAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required to avail this feature. Please update your profile..
        /// </summary>
        internal static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email delivery has failed..
        /// </summary>
        internal static string EmailDeliveryFailed {
            get {
                return ResourceManager.GetString("EmailDeliveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-existing email! Please use a working email..
        /// </summary>
        internal static string EmailNotExist {
            get {
                return ResourceManager.GetString("EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Parameter does not exist..
        /// </summary>
        internal static string EmailParameterNotExist {
            get {
                return ResourceManager.GetString("EmailParameterNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email containing the instructions to reset your password has been sent to {0}..
        /// </summary>
        internal static string EmailResetPasswordInstructionSent {
            get {
                return ResourceManager.GetString("EmailResetPasswordInstructionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template does not exist..
        /// </summary>
        internal static string EmailTemplateNotExist {
            get {
                return ResourceManager.GetString("EmailTemplateNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Shift Branch Inventory Detail does not exist..
        /// </summary>
        internal static string EndShiftBranchInventoryDetailNotExist {
            get {
                return ResourceManager.GetString("EndShiftBranchInventoryDetailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epayment is disabled..
        /// </summary>
        internal static string EpaymentDisabled {
            get {
                return ResourceManager.GetString("EpaymentDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epayment provider does not exist..
        /// </summary>
        internal static string EpaymentProviderNotExist {
            get {
                return ResourceManager.GetString("EpaymentProviderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epayment provider is null..
        /// </summary>
        internal static string EpaymentProviderNull {
            get {
                return ResourceManager.GetString("EpaymentProviderNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during parsing of email template..
        /// </summary>
        internal static string ErrorParsingEmailTemplate {
            get {
                return ResourceManager.GetString("ErrorParsingEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred saving file..
        /// </summary>
        internal static string ErrorSavingFile {
            get {
                return ResourceManager.GetString("ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending claim code to the email address. To get the code, please check the transaction history..
        /// </summary>
        internal static string ErrorSendingClaimCode {
            get {
                return ResourceManager.GetString("ErrorSendingClaimCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending password reset link to your email. Please try again later..
        /// </summary>
        internal static string ErrorSendingPasswordResetLink {
            get {
                return ResourceManager.GetString("ErrorSendingPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch from the transaction does not exist anymore. The system could not proceed with the voiding..
        /// </summary>
        internal static string ErrorVoidingBranchTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingBranchTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company from the transaction does not exist anymore. The system could not proceed with the voiding..
        /// </summary>
        internal static string ErrorVoidingCompanyTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingCompanyTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer account from the transaction does not exist anymore. The system could not proceed with the voiding..
        /// </summary>
        internal static string ErrorVoidingCustomerAccountTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingCustomerAccountTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guest from the transaction does not exist anymore. The system could not proceed with the voiding..
        /// </summary>
        internal static string ErrorVoidingGuestTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingGuestTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member from the transaction does not exist anymore. The system could not proceed with the voiding..
        /// </summary>
        internal static string ErrorVoidingMemberTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingMemberTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sales order from the transaction does not exist anymore. The system could not proceed with the voiding..
        /// </summary>
        internal static string ErrorVoidingSalesOrderTransactionNotExist {
            get {
                return ResourceManager.GetString("ErrorVoidingSalesOrderTransactionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eshop Code entered exceeded the allowed maximum length of 50 characters..
        /// </summary>
        internal static string EShopCodeExceedMaxLength {
            get {
                return ResourceManager.GetString("EShopCodeExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EShop Picture does not exist..
        /// </summary>
        internal static string EShopPictureNotExist {
            get {
                return ResourceManager.GetString("EShopPictureNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ does not exist.
        /// </summary>
        internal static string FAQNotExist {
            get {
                return ResourceManager.GetString("FAQNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to use this feature..
        /// </summary>
        internal static string FeatureNotAllowed {
            get {
                return ResourceManager.GetString("FeatureNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is only available to cybercafe members..
        /// </summary>
        internal static string FeatureOnlyAvailableToCybercafeMembers {
            get {
                return ResourceManager.GetString("FeatureOnlyAvailableToCybercafeMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field has an empty value.
        /// </summary>
        internal static string FieldEmpty {
            get {
                return ResourceManager.GetString("FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A filename can only be uploaded once per company..
        /// </summary>
        internal static string FilenameCanOnlyBeUploadedOnce {
            get {
                return ResourceManager.GetString("FilenameCanOnlyBeUploadedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeded {0} bytes..
        /// </summary>
        internal static string FileSizeExceeded {
            get {
                return ResourceManager.GetString("FileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Deduction Airtime does not exist..
        /// </summary>
        internal static string FullDeductionAirtimeNotExist {
            get {
                return ResourceManager.GetString("FullDeductionAirtimeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group does not exist..
        /// </summary>
        internal static string GroupNotExist {
            get {
                return ResourceManager.GetString("GroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. Guest account already expired..
        /// </summary>
        internal static string GuestAccountAlreadyExpired {
            get {
                return ResourceManager.GetString("GuestAccountAlreadyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Airtime does not exist..
        /// </summary>
        internal static string GuestAirtimeNotExist {
            get {
                return ResourceManager.GetString("GuestAirtimeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest not allowed to login to the specified branch..
        /// </summary>
        internal static string GuestNotAllowedToLogin {
            get {
                return ResourceManager.GetString("GuestNotAllowedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest does not exist.
        /// </summary>
        internal static string GuestNotExist {
            get {
                return ResourceManager.GetString("GuestNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect charging type found in customer session..
        /// </summary>
        internal static string IncorrectChargingType {
            get {
                return ResourceManager.GetString("IncorrectChargingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username/password..
        /// </summary>
        internal static string IncorrectUsernamePassword {
            get {
                return ResourceManager.GetString("IncorrectUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient available stock in inventory..
        /// </summary>
        internal static string InsufficientAvailableStockInventory {
            get {
                return ResourceManager.GetString("InsufficientAvailableStockInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an insufficient balance..
        /// </summary>
        internal static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient guest balance. The guest may have already used the amount..
        /// </summary>
        internal static string InsufficientGuestBalance {
            get {
                return ResourceManager.GetString("InsufficientGuestBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform debit action. Insufficient loyalty points..
        /// </summary>
        internal static string InsufficientLoyaltyPoints {
            get {
                return ResourceManager.GetString("InsufficientLoyaltyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient payment. Promo price is {0}..
        /// </summary>
        internal static string InsufficientPayment {
            get {
                return ResourceManager.GetString("InsufficientPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient toupup amount. Membership fee is {0}..
        /// </summary>
        internal static string InsufficientTopupAmount {
            get {
                return ResourceManager.GetString("InsufficientTopupAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string InternalServerError1 {
            get {
                return ResourceManager.GetString("InternalServerError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cashier session..
        /// </summary>
        internal static string InvalidCashierSession {
            get {
                return ResourceManager.GetString("InvalidCashierSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field value..
        /// </summary>
        internal static string InvalidFieldValue {
            get {
                return ResourceManager.GetString("InvalidFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image format..
        /// </summary>
        internal static string InvalidImageFormat {
            get {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP Address format..
        /// </summary>
        internal static string InvalidIPAddressFormat {
            get {
                return ResourceManager.GetString("InvalidIPAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login credentials..
        /// </summary>
        internal static string InvalidLoginCredentials {
            get {
                return ResourceManager.GetString("InvalidLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MAC Address format..
        /// </summary>
        internal static string InvalidMACAddressFormat {
            get {
                return ResourceManager.GetString("InvalidMACAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid page number..
        /// </summary>
        internal static string InvalidPageNumber {
            get {
                return ResourceManager.GetString("InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password reset token..
        /// </summary>
        internal static string InvalidPasswordResetToken {
            get {
                return ResourceManager.GetString("InvalidPasswordResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid payment type..
        /// </summary>
        internal static string InvalidPaymentType {
            get {
                return ResourceManager.GetString("InvalidPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PC name length..
        /// </summary>
        internal static string InvalidPCNameLength {
            get {
                return ResourceManager.GetString("InvalidPCNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PDF File..
        /// </summary>
        internal static string InvalidPDFFile {
            get {
                return ResourceManager.GetString("InvalidPDFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid redemption code..
        /// </summary>
        internal static string InvalidRedemptionCode {
            get {
                return ResourceManager.GetString("InvalidRedemptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session..
        /// </summary>
        internal static string InvalidSession {
            get {
                return ResourceManager.GetString("InvalidSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid status code..
        /// </summary>
        internal static string InvalidStatusCode {
            get {
                return ResourceManager.GetString("InvalidStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transfer token..
        /// </summary>
        internal static string InvalidTransferToken {
            get {
                return ResourceManager.GetString("InvalidTransferToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is not available for redemption..
        /// </summary>
        internal static string ItemNotAvailableForRedemption {
            get {
                return ResourceManager.GetString("ItemNotAvailableForRedemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is null..
        /// </summary>
        internal static string KeyNull {
            get {
                return ResourceManager.GetString("KeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key is invalid..
        /// </summary>
        internal static string LicenseKeyInvalid {
            get {
                return ResourceManager.GetString("LicenseKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have logged out..
        /// </summary>
        internal static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to login to this branch..
        /// </summary>
        internal static string LoginNotAllowed {
            get {
                return ResourceManager.GetString("LoginNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout successful..
        /// </summary>
        internal static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC address: {0} already in use in {1} branch..
        /// </summary>
        internal static string MACAddressAlreadyInUse {
            get {
                return ResourceManager.GetString("MACAddressAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC address {0} used by multiple cashier station..
        /// </summary>
        internal static string MACAddressUsedByMultipleCashierStation {
            get {
                return ResourceManager.GetString("MACAddressUsedByMultipleCashierStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topup amount has exceeded the cybercafe&apos;s maximum topup amount..
        /// </summary>
        internal static string MaxTopupAmountExceeded {
            get {
                return ResourceManager.GetString("MaxTopupAmountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum topup amount setting is not yet defined for this cybercafe..
        /// </summary>
        internal static string MaxTopupAmountNotDefined {
            get {
                return ResourceManager.GetString("MaxTopupAmountNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Unit does not exist..
        /// </summary>
        internal static string MeasurementUnitNotExist {
            get {
                return ResourceManager.GetString("MeasurementUnitNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Airtime does not exist..
        /// </summary>
        internal static string MemberAirtimeNotExist {
            get {
                return ResourceManager.GetString("MemberAirtimeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member has already accepted tnc!.
        /// </summary>
        internal static string MemberAlreadyAcceptedTNC {
            get {
                return ResourceManager.GetString("MemberAlreadyAcceptedTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member email is not verified..
        /// </summary>
        internal static string MemberEmailNotVerified {
            get {
                return ResourceManager.GetString("MemberEmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Hours Played not found..
        /// </summary>
        internal static string MemberHoursPlayedNotFound {
            get {
                return ResourceManager.GetString("MemberHoursPlayedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Loyalty Log does not exist..
        /// </summary>
        internal static string MemberLoyaltyLogNotExist {
            get {
                return ResourceManager.GetString("MemberLoyaltyLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Loyalty does not exist..
        /// </summary>
        internal static string MemberLoyaltyNotExist {
            get {
                return ResourceManager.GetString("MemberLoyaltyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member does not exist..
        /// </summary>
        internal static string MemberNotExist {
            get {
                return ResourceManager.GetString("MemberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member do not have registered email..
        /// </summary>
        internal static string MemberNotHaveRegisteredEmail {
            get {
                return ResourceManager.GetString("MemberNotHaveRegisteredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member is not yet enrolled with this cybercafe. Please topup first..
        /// </summary>
        internal static string MemberNotYetEnrolled {
            get {
                return ResourceManager.GetString("MemberNotYetEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrated File does not exist..
        /// </summary>
        internal static string MigratedFileNotExist {
            get {
                return ResourceManager.GetString("MigratedFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrated Member does not exist..
        /// </summary>
        internal static string MigratedMemberNotExist {
            get {
                return ResourceManager.GetString("MigratedMemberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Data Per Page or Page No fields..
        /// </summary>
        internal static string MissingDataPerPage {
            get {
                return ResourceManager.GetString("MissingDataPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm new password doesn&apos;t match..
        /// </summary>
        internal static string NewPasswordConfirmNewPasswordNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordConfirmNewPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password should be different from the old password..
        /// </summary>
        internal static string NewPasswordMatchOldPassword {
            get {
                return ResourceManager.GetString("NewPasswordMatchOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No airtime remaining..
        /// </summary>
        internal static string NoAirtimeRemaining {
            get {
                return ResourceManager.GetString("NoAirtimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coupon available..
        /// </summary>
        internal static string NoCouponAvailable {
            get {
                return ResourceManager.GetString("NoCouponAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no more codes available for the selected code type and denomination..
        /// </summary>
        internal static string NoMoreCodesAvailable {
            get {
                return ResourceManager.GetString("NoMoreCodesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non existing email. Please enter a working email address..
        /// </summary>
        internal static string NonExistingEmail {
            get {
                return ResourceManager.GetString("NonExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad does not exist..
        /// </summary>
        internal static string NotepadNotExist {
            get {
                return ResourceManager.GetString("NotepadNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect..
        /// </summary>
        internal static string OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order was already accepted..
        /// </summary>
        internal static string OrderAlreadyAccepted {
            get {
                return ResourceManager.GetString("OrderAlreadyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Expense Log does not exist..
        /// </summary>
        internal static string OtherExpenseLogNotExist {
            get {
                return ResourceManager.GetString("OtherExpenseLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is out of stock..
        /// </summary>
        internal static string OutOfStock {
            get {
                return ResourceManager.GetString("OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed..
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PC has not been properly configured. Please contact cashier for assistance..
        /// </summary>
        internal static string PCNotProperlyConfigured {
            get {
                return ResourceManager.GetString("PCNotProperlyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Order does not exist..
        /// </summary>
        internal static string PendingOrderNotExist {
            get {
                return ResourceManager.GetString("PendingOrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number..
        /// </summary>
        internal static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem was encountered while processing your request. Please contact the administrator..
        /// </summary>
        internal static string ProblemEncounteredWhileProcessingRequest {
            get {
                return ResourceManager.GetString("ProblemEncounteredWhileProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were problems with the given data..
        /// </summary>
        internal static string ProblemGivenData {
            get {
                return ResourceManager.GetString("ProblemGivenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id {0} is not available in branch&apos;s inventory..
        /// </summary>
        internal static string ProductIDNotAvailable {
            get {
                return ResourceManager.GetString("ProductIDNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product does not exist..
        /// </summary>
        internal static string ProductNotExist {
            get {
                return ResourceManager.GetString("ProductNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not cancel promo bacause it is already used..
        /// </summary>
        internal static string PromoAlreadyUsedCantCancel {
            get {
                return ResourceManager.GetString("PromoAlreadyUsedCantCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You still have a promo in use. Purchase has been rejected..
        /// </summary>
        internal static string PromoInUsePurchaseRejected {
            get {
                return ResourceManager.GetString("PromoInUsePurchaseRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo is not applicable for this customer type..
        /// </summary>
        internal static string PromoNotApplicableForCustomerType {
            get {
                return ResourceManager.GetString("PromoNotApplicableForCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo was not ended because a cashier is not available..
        /// </summary>
        internal static string PromoNotEndedCashierNotAvailable {
            get {
                return ResourceManager.GetString("PromoNotEndedCashierNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo does not eixst..
        /// </summary>
        internal static string PromoNotExist {
            get {
                return ResourceManager.GetString("PromoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo has been refunded successfully..
        /// </summary>
        internal static string PromoRefundedSuccesfully {
            get {
                return ResourceManager.GetString("PromoRefundedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Transaction Log does not exist..
        /// </summary>
        internal static string PromoTransactionLogNotExist {
            get {
                return ResourceManager.GetString("PromoTransactionLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo type is not supported..
        /// </summary>
        internal static string PromoTypeNotSupported {
            get {
                return ResourceManager.GetString("PromoTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an expiration date that is after today&apos;s date..
        /// </summary>
        internal static string ProvideExpirationDate {
            get {
                return ResourceManager.GetString("ProvideExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity should not be 0..
        /// </summary>
        internal static string QuantityZero {
            get {
                return ResourceManager.GetString("QuantityZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question already exists..
        /// </summary>
        internal static string QuestionAlreadyExist {
            get {
                return ResourceManager.GetString("QuestionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate is not configured for this station type..
        /// </summary>
        internal static string RateNotConfigured {
            get {
                return ResourceManager.GetString("RateNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate does not exist..
        /// </summary>
        internal static string RateNotExist {
            get {
                return ResourceManager.GetString("RateNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason must be less than {0} characters..
        /// </summary>
        internal static string ReasonMaxLength {
            get {
                return ResourceManager.GetString("ReasonMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region does not exist..
        /// </summary>
        internal static string RegionNotExist {
            get {
                return ResourceManager.GetString("RegionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection reason is required..
        /// </summary>
        internal static string RejectionReasonRequired {
            get {
                return ResourceManager.GetString("RejectionReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request denied..
        /// </summary>
        internal static string RequestDenied {
            get {
                return ResourceManager.GetString("RequestDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requesting member do not own this code..
        /// </summary>
        internal static string RequestingMemberNotOwnCode {
            get {
                return ResourceManager.GetString("RequestingMemberNotOwnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required points is not equal with the server..
        /// </summary>
        internal static string RequiredPointsNotEqualToServer {
            get {
                return ResourceManager.GetString("RequiredPointsNotEqualToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The retail id {0} is not for sale in branch: {1}..
        /// </summary>
        internal static string RetailIDNotForSale {
            get {
                return ResourceManager.GetString("RetailIDNotForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail does not exist..
        /// </summary>
        internal static string RetailNotExist {
            get {
                return ResourceManager.GetString("RetailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Adjustment does not exist..
        /// </summary>
        internal static string SalesAdjustmentNotExist {
            get {
                return ResourceManager.GetString("SalesAdjustmentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order does not exist..
        /// </summary>
        internal static string SalesOrderNotExist {
            get {
                return ResourceManager.GetString("SalesOrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesRetail does not exist..
        /// </summary>
        internal static string SalesRetailNotExist {
            get {
                return ResourceManager.GetString("SalesRetailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file is not an image..
        /// </summary>
        internal static string SelectedFileNotImage {
            get {
                return ResourceManager.GetString("SelectedFileNotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session has already been replaced..
        /// </summary>
        internal static string SessionAlreadyReplaced {
            get {
                return ResourceManager.GetString("SessionAlreadyReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session does not exist..
        /// </summary>
        internal static string SessionNotExist {
            get {
                return ResourceManager.GetString("SessionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shift has already ended..
        /// </summary>
        internal static string ShiftAlreadyEnded {
            get {
                return ResourceManager.GetString("ShiftAlreadyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Detail does not exist..
        /// </summary>
        internal static string ShiftDetailNotExist {
            get {
                return ResourceManager.GetString("ShiftDetailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift does not exist..
        /// </summary>
        internal static string ShiftNotExist {
            get {
                return ResourceManager.GetString("ShiftNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Picture does not exist..
        /// </summary>
        internal static string ShopPictureNotExist {
            get {
                return ResourceManager.GetString("ShopPictureNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Transaction Log does not exist.
        /// </summary>
        internal static string ShopTransactionLogNotExist {
            get {
                return ResourceManager.GetString("ShopTransactionLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Version does not exist..
        /// </summary>
        internal static string SoftwareVersionNotExist {
            get {
                return ResourceManager.GetString("SoftwareVersionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between Start Date and End Date should not be greater than 7 days..
        /// </summary>
        internal static string StartDateEndDateDifferenceGreaterThan7Days {
            get {
                return ResourceManager.GetString("StartDateEndDateDifferenceGreaterThan7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date cannot be greater than End Date.
        /// </summary>
        internal static string StartDateGreaterThanEndDate {
            get {
                return ResourceManager.GetString("StartDateGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station with ip address {0} for Branch {1} of Company {2} already exists..
        /// </summary>
        internal static string StationIPAlreadyExist {
            get {
                return ResourceManager.GetString("StationIPAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station with name &quot; + {0} + &quot; for Branch &quot; + {1} + &quot; of Company &quot; + {2} + &quot; already exists..
        /// </summary>
        internal static string StationNameAlreadyExist {
            get {
                return ResourceManager.GetString("StationNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station does not exist..
        /// </summary>
        internal static string StationNotExist {
            get {
                return ResourceManager.GetString("StationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station rates are not configured for this station and member type..
        /// </summary>
        internal static string StationRateNotConfigured {
            get {
                return ResourceManager.GetString("StationRateNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station registration is successful..
        /// </summary>
        internal static string StationRegistrationSuccesful {
            get {
                return ResourceManager.GetString("StationRegistrationSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are still logged in to another PC on {0} - {1}..
        /// </summary>
        internal static string StillLoggedIn {
            get {
                return ResourceManager.GetString("StillLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are still logged-in on a different computer..
        /// </summary>
        internal static string StillLoggedIn1 {
            get {
                return ResourceManager.GetString("StillLoggedIn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Contact Detail does not exist..
        /// </summary>
        internal static string SupportContactDetailNotExist {
            get {
                return ResourceManager.GetString("SupportContactDetailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration does not exist..
        /// </summary>
        internal static string SystemConfigurationNotExist {
            get {
                return ResourceManager.GetString("SystemConfigurationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician is not allowed to login to the specified branch.
        /// </summary>
        internal static string TechnicianNotAllowedToLogin {
            get {
                return ResourceManager.GetString("TechnicianNotAllowedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician does not exist.
        /// </summary>
        internal static string TechnicianNotExist {
            get {
                return ResourceManager.GetString("TechnicianNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions does not exist..
        /// </summary>
        internal static string TNCNotExist {
            get {
                return ResourceManager.GetString("TNCNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient toupup amount. Membership fee is {0} and promo price is {1}..
        /// </summary>
        internal static string TopupAmountInsufficient {
            get {
                return ResourceManager.GetString("TopupAmountInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction already has a pending adjustment request..
        /// </summary>
        internal static string TransactionAlreadyHasPendingAdjustmentRequest {
            get {
                return ResourceManager.GetString("TransactionAlreadyHasPendingAdjustmentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction has already been voided..
        /// </summary>
        internal static string TransactionAlreadyVoided {
            get {
                return ResourceManager.GetString("TransactionAlreadyVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Log does not exist.
        /// </summary>
        internal static string TransactionLogNotExist {
            get {
                return ResourceManager.GetString("TransactionLogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Log not owned by user..
        /// </summary>
        internal static string TransactionLogNotOwned {
            get {
                return ResourceManager.GetString("TransactionLogNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer token has expired..
        /// </summary>
        internal static string TransferTokenExpired {
            get {
                return ResourceManager.GetString("TransferTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Token does not exist..
        /// </summary>
        internal static string TransferTokenNotExist {
            get {
                return ResourceManager.GetString("TransferTokenNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to communicate with backend server. Please proceed to the cashier for help..
        /// </summary>
        internal static string UnableToCommunicateToBackend {
            get {
                return ResourceManager.GetString("UnableToCommunicateToBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is deactivated..
        /// </summary>
        internal static string UserAccountDeactivated {
            get {
                return ResourceManager.GetString("UserAccountDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group does not exist.
        /// </summary>
        internal static string UserGroupNotExist {
            get {
                return ResourceManager.GetString("UserGroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists..
        /// </summary>
        internal static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session of user from the station was successfully removed..
        /// </summary>
        internal static string UserSessionRemoved {
            get {
                return ResourceManager.GetString("UserSessionRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voiding has been disabled for this merchant..
        /// </summary>
        internal static string VoidingDisbaled {
            get {
                return ResourceManager.GetString("VoidingDisbaled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to void this transaction..
        /// </summary>
        internal static string VoidTransactionNotAllowed {
            get {
                return ResourceManager.GetString("VoidTransactionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet error was encounted..
        /// </summary>
        internal static string WalletError {
            get {
                return ResourceManager.GetString("WalletError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet transaction log does not exist..
        /// </summary>
        internal static string WalletTransactionNotExist {
            get {
                return ResourceManager.GetString("WalletTransactionNotExist", resourceCulture);
            }
        }
    }
}
